### ISSUE TITLE
Pointcloud2 data reading with the driver

### ISSUE THREAD

**Issue by mxrchn** [ros-drivers/velodyne#100]
hi, jack, I use the driver to read point cloud data with the command: $ rostopic echo / velodyne_points.
But I can't understand the "data" means.   So how to read x, y, z coordinates from these numbers? Thanks!
The attached file is the picture of these numbers. @jack-oquin
![screenshot from 2016-08-04 20-29-34](https://cloud.githubusercontent.com/assets/16284639/17401966/371ec65a-5a83-11e6-9afd-295c783d70d0.png)

**Comment by mxrchn** [comment]
It's velodyne VLP-16.

**Comment by jack-oquin** [comment]
That topic publishes ``sensor_msgs/PointCloud2`` messages. It's not useful to view them with ``rostopic echo``. You can view the data with rviz:
```
rosrun rviz rviz -f velodyne
```

* In the "displays" panel, click "Add", then select "Point Cloud2", then press "OK".
* In the "Topic" field of the new "Point Cloud2" tab, enter "/velodyne_points".

**Comment by jack-oquin** [comment]
Questions like this are better sent to answers.ros.org.
