### ISSUE TITLE
Where is the origin of coordinates

### ISSUE THREAD

**Issue by mxrchn** [ros-drivers/velodyne#102]
When I read the rawdata.cc file in the driver, it's hard for me to understand where the origin of coordinates is. If the origin of coordinates is unclear, the calibration and final PointCloud2 published may be inaccurate. Below is the several lines of code in rawdata.cc. So can you tell me where  the origin of coordinates is, the geometric centre of subface or inside the VLP-16?
Thank you in advance! @jack-oquin
![screenshot from 2016-08-10 20-03-05](https://cloud.githubusercontent.com/assets/16284639/17553047/358b07ec-5f36-11e6-81bb-8e072f49b196.png)

**Comment by jlblancoc** [comment]
The reference frame for the read point clouds, it's **inside** the Velodyne
cylinder, approximately at the middle point of the cylinder.

**Comment by jack-oquin** [comment]
Yes, that's where you should define the ``velodyne``  frame of reference, relative to your vehicle base.

**Comment by mxrchn** [comment]
Is the origin of coordinates in the same height of the optical centre? [37.7]/1.485?
![centre](https://cloud.githubusercontent.com/assets/16284639/17576783/31e5d220-5fa9-11e6-8d0c-9228eca78b92.png)

**Comment by jlblancoc** [comment]
I think that's correct, that is the **nominal** origin of coordinates. There is a set of calibration parameters to introduce some offsets wrt that point, though.

**Comment by chukcha2** [comment]
VLP-16 manual, on page 48 has more details on this but I don't completely understand it yet. Note this line "APPLY VERTICAL CORRECTION FOR GREATEST ACCURACY".

![vlpdrawing](https://cloud.githubusercontent.com/assets/8009504/17600443/868f2dd0-5fd1-11e6-810c-31fd48b70e16.png)

**Comment by B-Leslie** [comment]
@chukcha2 , I believe each beam has its own detector, and the detectors are arranged in a vertical array. The beams are therefore focused on to different points inside the scanner, and so a small vertical offset corresponding to these different focal points (as specified on the RHS of the diagram on p. 48) should be applied to scan points based on the beam ID.

**Comment by jack-oquin** [comment]
Is this question answered satisfactorily? If so, please close the issue.

**Comment by siyangy** [comment]
A related question: how does the point get transformed from "velodyne" frame to "odom" frame? Didn't find a StampedTransform provided anywhere in this code repo.

**Comment by jack-oquin** [comment]
It's done here: https://github.com/ros-drivers/velodyne/blob/master/velodyne_pointcloud/src/conversions/transform.cc#L104
