### ISSUE TITLE
devip_ of InputSocket is not been assigned

### ISSUE THREAD

**Issue by zhixy** [ros-drivers/velodyne#107]
I try to use two velodyne together, so I need to specify ip address, however, I find it doesn't work when I change it in .launch file. I checked the source, and found that there is no assignment to devip_ at all, after  I add "inet_aton(devip_str_.c_str(), &devip_);" in Constructor of InputSocket, it works.

**Comment by jack-oquin** [comment]
Would you like to provide a pull request to fix this?

**Comment by zhixy** [comment]
Of course, but I found that the first pull request upload by teosnare is just to solve this issue before I want to upload my pull request, so I think I don't need to do it any more.

**Comment by jack-oquin** [comment]
Merged #101, please close this if that fixes it.

**Comment by zhixy** [comment]
yes, thx
