### ISSUE TITLE
How to set the View_width and View_directions on VLP16?

### ISSUE THREAD

**Issue by matheusns** [ros-drivers/velodyne#114]
I've been trying to set those parameters on VLP16, but i can't find the necessary arguments.

**Comment by jack-oquin** [comment]
Those parameters are named ``view_width`` and ``view_direction``.

See: [velodyne_pointcloud parameters](http://wiki.ros.org/velodyne_pointcloud#Parameters-1)

**Comment by matheusns** [comment]
Thanks @jack-oquin, but it isn't too explicit. I've been looking for a way to do that and I've gotten that through the "~$ rosservice call /velodyne_nodelet_manager_cloud/set_parameters". Thanks for all. Nice Job!

**Comment by jack-oquin** [comment]
[rqt_reconfigure](http://wiki.ros.org/rqt_reconfigure) is a good tool for interactively setting these and other parameters.
