### ISSUE TITLE
Getting positioning data from velodyne 

### ISSUE THREAD

**Issue by mkschreder** [ros-drivers/velodyne#117]
Is it possible to calculate relative positioning from velodyne data using this package? Is there a guide somewhere on how to do it?

**Comment by jack-oquin** [comment]
Sorry for the very slow response. This package is just a device driver. It does not do localization, but provides data from which other packages may operate.

This kind of question is more appropriate for http://answers.ros.org. It will get the attention of a wider audience. Please use the ``velodyne`` tag and some others like ``localization``, etc.
