### ISSUE TITLE
VLP-16 doesn't send data packet, only position packet

### ISSUE THREAD

**Issue by hcv1027** [ros-drivers/velodyne#124]
My working environment (Ubuntu 16.04 + ROS Kinetic) can't catch the data packet from VLP-16 correctly.
It seems that VLP-16 dose not send data packet.
I used wireshark to monitor the received packet from VLP-16.
It shows that VLP-16 only sends position packet, but no data packet.
Below is the screen shot.
Can someone help me to debug this problem?
![2017-08-03 15-33-17](https://user-images.githubusercontent.com/12728923/28911958-cd9ab8e6-7864-11e7-93b0-180eefea46b8.png)
![2017-08-03 15-22-12](https://user-images.githubusercontent.com/12728923/28911965-d3ca0ce4-7864-11e7-8afe-5fe48c59041d.png)

**Comment by jlblancoc** [comment]
Hi @hcv1027 

Those 512 B packets are *not* scan data (UDP port 2368), but "telemetry" packets (UDP port 8308). They are all zero because, I guess, the LiDAR is not connected to a GPS source, right? Those packets are populated with an NMEA frame, when available from a GPS. 

Your problem is, apparently, that the LiDAR is not emitting range data. Try clicking on "laser: off" -> save; (wait 1 minute), "laser: on" -> save, and see if something changes.

**Comment by hcv1027** [comment]
Hi @jlblancoc 
If the save you said is "Save configuration" button, then I just tried and it did not work.
It still only sends "telemetry" packets.
Any other suggestion?

**Comment by h3ct0r** [comment]
Have you tried to set the destination IP address to your ROS master IP?

**Comment by JWhitleyAStuff** [comment]
@jlblancoc - I would recommend you contact Velodyne on this issue. This is something related to either the configuration (though that looks correct) or the proper functioning of your device. I am closing this issue as off-topic (since it isn't related to the ROS driver)

**Comment by jlblancoc** [comment]
Sure @JWhitleyAStuff close it!
But it was @hcv1027 not me who was having troubles ;-)

Cheers

**Comment by JWhitleyAStuff** [comment]
Thanks for the correction, @jlblancoc.

**Comment by wawaafan** [comment]
Do you have resolve this problem?  I also meet the same question, could you tell me how to resolve this?

**Comment by jack-oquin** [comment]
The destination IP of 255.255.255.255 looks wrong. Have you tried setting the actual IP address?

**Comment by saikishor** [comment]
@jack-oquin is having destination IP as 255.255.255.255 wrong?. I have a velodyne sensor. I connected it to my network, it works very well, but I am not able to access its webpage to configure stuff. Any idea how to recover to the original settings?
![image](https://user-images.githubusercontent.com/10082428/47148012-cb8ed980-d2cf-11e8-9c6b-f0e5b01db602.png)

**Comment by duchengyao** [comment]
make sure  TTL in PPS and RS232 in GPRMC

**Comment by yasmeenel3sh** [comment]
@duchengyao I am having the same problem now ,but I am sure the correct signals are connected in the correct places , though what happens is in the web interface it shows that the pps is locked and it shows the pps position, however on wire shark the nmea gprmc packet isnot being send by veloyne ,what could be the reason for that?

**Comment by JWhitleyAStuff** [comment]
@yasmeenel3sh - This is a *very old* ticket. Could you please create a new one if you are still having problems?

**Comment by OxMarco** [comment]
I am getting the same issue, if you solved the problem it would be good to have some info on how to do it

**Comment by fluffyluv** [comment]
Still same problem...
