### ISSUE TITLE
[Enhacement] Adding parameter to avoid publication of inf values on range field

### ISSUE THREAD

**Issue by B0gdar** [ros-drivers/velodyne#132]
By making a quick review on the [VelodyneLaserScan class](https://github.com/ros-drivers/velodyne/blob/master/velodyne_laserscan/src/VelodyneLaserScan.cpp), at VelodyneLaserScan::recvCallback when constructing the LaserScanMessage there is no option for removing inf values of the published scan. I know that this is a common feature on other packages so it should not be difficult to include it
```c++
//line 109
scan->ranges.resize(SIZE, INFINITY);
if ((offset_x == 0) && (offset_y == 4) && (offset_z == 8) && (offset_i == 16) && (offset_r == 20)) {
      scan->intensities.resize(SIZE);
      for (sensor_msgs::PointCloud2ConstIterator<float> it(*msg, "x"); it != it.end(); ++it) {
        const uint16_t r = *((const uint16_t*)(&it[5])); // ring
        if (r == ring) {
          const float x = it[0]; // x
          const float y = it[1]; // y
          const float i = it[4]; // intensity
          const int bin = (atan2f(y, x) + (float)M_PI) / RESOLUTION;
          if ((bin >= 0) && (bin < (int)SIZE)) {
            scan->ranges[bin] = sqrtf(x * x + y * y);
            scan->intensities[bin] = i;
          }
        }
}
```
As it is displayed, there is no control for removing Inf values from range field. There should be a parameter like in [pointcloud_to_laserscan](https://github.com/ros-perception/pointcloud_to_laserscan/blob/indigo-devel/src/pointcloud_to_laserscan_nodelet.cpp) that controls if to substitute `Inf` for `range_max+1` value.

```c++
//line 143
sensor_msgs::LaserScan output;
//(...)
//line 161
//determine if laserscan rays with no obstacle data will evaluate to infinity or max_range
    if (use_inf_)
    {
      output.ranges.assign(ranges_size, std::numeric_limits<double>::infinity());
    }
    else
    {
      output.ranges.assign(ranges_size, output.range_max + 1.0);
}

```

**Comment by JWhitleyAStuff** [comment]
This has been implemented correctly according to REP 117 (http://www.ros.org/reps/rep-0117.html). Unless there is a significant need to have a different (non-conforming) value for out-of-range returns, I'm inclined to leave it.
