### ISSUE TITLE
Documentation should be clearer about stack capabilities

### ISSUE THREAD

**Issue by B0gdar** [ros-drivers/velodyne#152]
Running the driver with a VLP16. I assumed that the driver would set the specified rpm on the hardware when it does not. The parameter sets expected receiveing packets frequency :
```cpp 
//driver.cc lines 73 to 81
private_nh.param("rpm", config_.rpm, 600.0);
  ROS_INFO_STREAM(deviceName << " rotating at " << config_.rpm << " RPM");
  double frequency = (config_.rpm / 60.0);     // expected Hz rate

  // default number of packets for each scan is a single revolution
  // (fractions rounded up)
  config_.npackets = (int) ceil(packet_rate / frequency);
  private_nh.getParam("npackets", config_.npackets);
ROS_INFO_STREAM("publishing " << config_.npackets << " packets per scan");
```
Then uses npackets for diagnosis based on received packets from velodyne and packets configuration.
So specified rpms may differ form real motor rpms of the sensor.

I understand complexity which that work would imply. Given the case that there are labs in which different teams share same velodyne, configurations on the phsyical device may differ. A clearer explanation on the documentation would save many people time.

**Thank you for the effort made to build this stack!**

**Comment by JWhitleyAStuff** [comment]
@B0gdar / @versatran01 - Thanks for the feedback. I have added issue #199 to address this. I'll try to get on it as soon as I can. Any help from others is appreciated.
