### ISSUE TITLE
Unable to open calibration file VeloView-VLP-16-HiRes.xml

### ISSUE THREAD

**Issue by phs4530** [ros-drivers/velodyne#153]
Unable to open calibration file: 
/home/hs/VeloView-VLP-16-HiRes.xml

ubuntu 16.04
ros kinetic

**Comment by JWhitleyAStuff** [comment]
@phs4530 - Sorry for the delayed response. The xml file provided by Velodyne for the calibration of your VLP-16 HiRes must be first converted into a yaml file for use with the ROS driver. Please see section 4 of http://wiki.ros.org/velodyne_pointcloud?distro=kinetic for more information.
