### ISSUE TITLE
what does the data array mean printed by the "rostopic echo /velodyne_points"

### ISSUE THREAD

**Issue by melodynk** [ros-drivers/velodyne#158]
I would like know what these integers mean?I notice that 32 integers correspond with one cloud point. Is there any introduction about these data's meaning printed by the ROS?Thanks! 

![point_cloud_ros](https://user-images.githubusercontent.com/37090372/37951186-229a68c8-31ce-11e8-9c1c-07790145990c.jpg)

**Comment by JWhitleyAStuff** [comment]
This array is part of a sensor_msgs/PointCloud2 message. See http://docs.ros.org/api/sensor_msgs/html/msg/PointCloud2.html for more details. The raw data aren't very useful but when they're imported into a receiving node and converted to a pcl::PointCloud2, they're organized and tagged with metadata (in this case, intensity).
