### ISSUE TITLE
how to adjust the frequency of the publish topic /scan

### ISSUE THREAD

**Issue by Sun1307010608** [ros-drivers/velodyne#168]
Hi everyone:
  I use this ros-drivers to receive the topics named /scan, and when I input the command: "rostopic hz /scan", It shows：
average rate: 9.814
	min: 0.088s max: 10.302s std dev: 0.10281s window: 9
average rate: 9.814
	min: 0.088s max: 10.302s std dev: 0.10276s window: 19
average rate: 9.814
	min: 0.088s max: 10.302s std dev: 0.10271s window: 29
average rate: 9.814
	min: 0.088s max: 10.302s std dev: 0.10266s window: 39
average rate: 9.814
	min: 0.088s max: 10.302s std dev: 0.10261s window: 39
average rate: 9.815
	min: 0.088s max: 10.302s std dev: 0.10255s window: 49
...
,dose it means the frequency of /scan topic is 10Hz, How can I change the publish frequency of /scan

**Comment by JWhitleyAStuff** [comment]
The publish frequency of the /scan topic is determined by the rotation rate of the sensor (RPM) divided by 60. If the sensor is spinning at 600 RPM (default), this will result in a 10 Hz frequency on the /scan topic. See the documentation for the HDL-64E for more information: http://www.velodynelidar.com/lidar/products/manual/HDL-64E%20Manual.pdf

From page 8:

> The HDL-64E can spin at rates ranging from 300 RPM (5 Hz) to 900 RPM (15 Hz). The default
is 600 RPM (10 Hz). Note that changing the spin rate does not change the data rate – the
unit will send out the same number of packets (at a rate of one million data points per second)
regardless of spin rate. The image resolution will increase or decrease depending on rotation
speed. See Appendix B for angular resolution figures for various spin rates.
