### ISSUE TITLE
Migrating to ROS Melodic

### ISSUE THREAD

**Issue by Alby407** [ros-drivers/velodyne#171]
Is there already a date when the package will be migrated/updated to ROS Melodic?

**Comment by JWhitleyAStuff** [comment]
There is no particular date but I'm working on adding Melodic to the list of test builds right now. After it is stable in Melodic and I've pulled the two PRs that need testing (#164 and #155), I'll make a new release for Kinetic, Lunar, and Melodic.

**Comment by JWhitleyAStuff** [comment]
It is now building on Travis for Indigo, Kinetic, Lunar, and Melodic. As I said, I want to test changes on the two PRs and get them merged before releasing but I'll update this ticket when the new version is out.

**Comment by Alby407** [comment]
Thank you very much!

**Comment by JWhitleyAStuff** [comment]
Sorry this took so incredibly long. I just released v1.4.0 which is being built on the ROS build farm for Indigo, Kinetic, Lunar, and Melodic. I didn't get all of the PRs in that I wanted but a release was really necessary.
