### ISSUE TITLE
Unable to locate package ros-jade-velodyne

### ISSUE THREAD

**Issue by StanleyHusai** [ros-drivers/velodyne#179]
I used "sudo apt-get install ros-jade-velodyne" to install velodyne-driver but it didn't work. it shows as follow:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ros-jade-velodyne

My ubuntu is 14.04, my ros version is jade. i don't know where the problem is. Thanks for your answers!

**Comment by JWhitleyAStuff** [comment]
@StanleyHusai - It doesn't look like there is currently a Velodyne package released for Jade. I don't know the history of this repository well enough to say why this is the case (maybe @jack-oquin could help) but Jade is no longer supported (by this repository or ROS in general). I would recommend you moving back to Indigo or, better yet, forward to Kinetic or Melodic.
