### ISSUE TITLE
Wrong dimensions of objects

### ISSUE THREAD

**Issue by ashnarayan13** [ros-drivers/velodyne#181]
Hi, 

I have pcap recording on a VLP32c lidar. The size of a measured object is wrong by almost half in the scan data when viewed with rviz. Is there some scaling done for the points? The height of a standard pylon and the distance between pylons is nearly half the length that was physically measured. 
Any idea how to fix this?

Thanks!

**Comment by ashnarayan13** [comment]
@JWhitleyAStuff - The maint/vlp_32c_support has proper scale. But the scan is not consistent and flickers. 
![imageedit_4_5823894109](https://user-images.githubusercontent.com/6239730/44255150-59cddd00-a205-11e8-813b-eec27e888285.png)

You can see the rotation of the LiDAR scan. This didn't happen in the master branch. Any ideas on how to fix it? This issue doesn't happen on veloview as well. 

Thanks!

**Comment by JWhitleyAStuff** [comment]
@ashnarayan13 - The maint/vlp_32_c branch was several PRs behind master. I've updated it and merged. Please pull, rebuild, and try this branch again. Thanks.

**Comment by ashnarayan13** [comment]
Hi, 
The issue is resolved! 
Thank you.
