### ISSUE TITLE
hello. can i ask something ?

### ISSUE THREAD

**Issue by ohwonteak** [ros-drivers/velodyne#182]
i use velodyne lidar vlp16 and i want to list data like this

first i want to list vertical data like -15deg -13deg -11deg ......15deg but now data come like -15deg ->1deg->-13deg->3deg .....15deg
If i know the moment when the horizontal information(next vertical data start,X-Y angle?) changes, is there a way to know that information is sortable?

**Comment by msemtd** [comment]
To get the points in increasing elevation, you can sort the points in each PointCloud2 message by ring in the following ring order: 0, 2, 4, 6, 8, 10, 12, 14, 1, 3, 5, 7, 9, 11, 13, 15 as per the VLP-16 User Manual Table 9-1
