### ISSUE TITLE
Are velodyne points ordered?

### ISSUE THREAD

**Issue by versatran01** [ros-drivers/velodyne#197]
Does anyone know what is the direction of rotation of the lidar, is it CW or CCW? 
And is it safe to say that points published by the driver are ordered? For example, if I simply iterate through the points, then earlier points will come from a ring with lower id than later points, and within each ring, points start from degree 0 to 360?

**Comment by JWhitleyAStuff** [comment]
@versatran01 - This is somewhat unscientific but, using a camera with no IR filter, the lasers appear to spin counter-clockwise about Z (with Z pointing up). However, the points are currently unstructured within the point cloud. There is some information regarding the ordering of the rings in #182 and PR #74 attempts to address this issue. However, that PR has not been worked on in a while. If you would like to help by updating the PR with the current `master` codebase and testing, it would be much appreciated!

**Comment by versatran01** [comment]
I see, so one should not assume any order at this point.
I'd love to help, there seems to be two approaches, one is to directly produce ordered point cloud (probably do it in raw_data.cc0), the other is to post process the pointcloud, since one can always compute azimuth and inclination of a point given x,y,z. Which do you think is better?

**Comment by JWhitleyAStuff** [comment]
@versatran01 - Approaches that have been attempted before centered around processing the point cloud as soon as it arrives. This would be my preferred approach, as long as it is efficient and does not reduce the frequency of the produced point clouds by much.

**Comment by versatran01** [comment]
@JWhitleyAStuff After playing around myself for a bit, I'm proposing to use a range image as intermediate storage for getting ordered point cloud. 

The way it works is that instead of unpacking data directly into a point cloud, we put it in a `sensor_msgs::Image` and put relevant information in `sensor_msgs::CameraInfo` and publish these using image_transport. The image is (num beams x num of points per revolution), the value in each pixel is range encoded in uint16_t and camera info contains information such as horizontal and vertical angular range and resolution, min and max range, etc. The image together with camera info contains enough information if one wants to restore the point cloud from it. 

The good thing about using an image is that it is already ordered, each row represents one beam and pixels within that row are ordered also by azimuth. Bagging this range image instead of point cloud give huge storage reduction. (I tested with my bag of 460M cloud and the new one is just 30M). The downside is that this introduces dependencies on image_transport, Image and CameraInfo. And due to noise in point cloud and discretization, the restored point cloud has fewer points than the original one. 
Speedwise converting cloud to range image takes about 3ms on my 4th gen i7 computer in a single thread. 

Let me know what you thinks, I'd be happy to answer any questions and concerns.
