### ISSUE TITLE
Velodyne Puck Lite - Points are not projected correctly | Wrong measurement of scanned points

### ISSUE THREAD

**Issue by pavankumarbn** [ros-drivers/velodyne#202]
Hi All,

I am using  Velodyne Puck Lite for PCD acquisition, but after the scan, data appears to be distorted horizontally, Projected points are not clearly aligned with each channel data.  
<img width="868" alt="pcd" src="https://user-images.githubusercontent.com/4351074/49851481-8d6feb00-fe24-11e8-9cbc-2f04dcea7aea.png">

<img width="672" alt="pcd2" src="https://user-images.githubusercontent.com/4351074/49852571-dc6b4f80-fe27-11e8-8e53-9c13582fe412.png">

Velodyne is mounted on Drone to acquire the data.

This is  the launch file

  
![2018-12-12_15-51-59](https://user-images.githubusercontent.com/4351074/49852153-a4afd800-fe26-11e8-8e24-1374963c0f5b.png)

////// calibrationfile   VLP16db.yaml

`lasers:
- {dist_correction: 0.0, dist_correction_x: 0.0, dist_correction_y: 0.0, focal_distance: 0.0,
  focal_slope: 0.0, horiz_offset_correction: 0.0, laser_id: 0, rot_correction: 0.0,
  vert_correction: -0.2617993877991494, vert_offset_correction: 0.0}
- {dist_correction: 0.0, dist_correction_x: 0.0, dist_correction_y: 0.0, focal_distance: 0.0,
  focal_slope: 0.0, horiz_offset_correction: 0.0, laser_id: 1, rot_correction: 0.0,
  vert_correction: 0.017453292519943295, vert_offset_correction: 0.0}
- {dist_correction: 0.0, dist_correction_x: 0.0, dist_correction_y: 0.0, focal_distance: 0.0,
  focal_slope: 0.0, horiz_offset_correction: 0.0, laser_id: 2, rot_correction: 0.0,
  vert_correction: -0.22689280275926285, vert_offset_correction: 0.0}
- {dist_correction: 0.0, dist_correction_x: 0.0, dist_correction_y: 0.0, focal_distance: 0.0,
  focal_slope: 0.0, horiz_offset_correction: 0.0, laser_id: 3, rot_correction: 0.0,
  vert_correction: 0.05235987755982989, vert_offset_correction: 0.0}
- {dist_correction: 0.0, dist_correction_x: 0.0, dist_correction_y: 0.0, focal_distance: 0.0,
  focal_slope: 0.0, horiz_offset_correction: 0.0, laser_id: 4, rot_correction: 0.0,
  vert_correction: -0.19198621771937624, vert_offset_correction: 0.0}
- {dist_correction: 0.0, dist_correction_x: 0.0, dist_correction_y: 0.0, focal_distance: 0.0,
  focal_slope: 0.0, horiz_offset_correction: 0.0, laser_id: 5, rot_correction: 0.0,
  vert_correction: 0.08726646259971647, vert_offset_correction: 0.0}
- {dist_correction: 0.0, dist_correction_x: 0.0, dist_correction_y: 0.0, focal_distance: 0.0,
  focal_slope: 0.0, horiz_offset_correction: 0.0, laser_id: 6, rot_correction: 0.0,
  vert_correction: -0.15707963267948966, vert_offset_correction: 0.0}
- {dist_correction: 0.0, dist_correction_x: 0.0, dist_correction_y: 0.0, focal_distance: 0.0,
  focal_slope: 0.0, horiz_offset_correction: 0.0, laser_id: 7, rot_correction: 0.0,
  vert_correction: 0.12217304763960307, vert_offset_correction: 0.0}
- {dist_correction: 0.0, dist_correction_x: 0.0, dist_correction_y: 0.0, focal_distance: 0.0,
  focal_slope: 0.0, horiz_offset_correction: 0.0, laser_id: 8, rot_correction: 0.0,
  vert_correction: -0.12217304763960307, vert_offset_correction: 0.0}
- {dist_correction: 0.0, dist_correction_x: 0.0, dist_correction_y: 0.0, focal_distance: 0.0,
  focal_slope: 0.0, horiz_offset_correction: 0.0, laser_id: 9, rot_correction: 0.0,
  vert_correction: 0.15707963267948966, vert_offset_correction: 0.0}
- {dist_correction: 0.0, dist_correction_x: 0.0, dist_correction_y: 0.0, focal_distance: 0.0,
  focal_slope: 0.0, horiz_offset_correction: 0.0, laser_id: 10, rot_correction: 0.0,
  vert_correction: -0.08726646259971647, vert_offset_correction: 0.0}
- {dist_correction: 0.0, dist_correction_x: 0.0, dist_correction_y: 0.0, focal_distance: 0.0,
  focal_slope: 0.0, horiz_offset_correction: 0.0, laser_id: 11, rot_correction: 0.0,
  vert_correction: 0.19198621771937624, vert_offset_correction: 0.0}
- {dist_correction: 0.0, dist_correction_x: 0.0, dist_correction_y: 0.0, focal_distance: 0.0,
  focal_slope: 0.0, horiz_offset_correction: 0.0, laser_id: 12, rot_correction: 0.0,
  vert_correction: -0.05235987755982989, vert_offset_correction: 0.0}
- {dist_correction: 0.0, dist_correction_x: 0.0, dist_correction_y: 0.0, focal_distance: 0.0,
  focal_slope: 0.0, horiz_offset_correction: 0.0, laser_id: 13, rot_correction: 0.0,
  vert_correction: 0.22689280275926285, vert_offset_correction: 0.0}
- {dist_correction: 0.0, dist_correction_x: 0.0, dist_correction_y: 0.0, focal_distance: 0.0,
  focal_slope: 0.0, horiz_offset_correction: 0.0, laser_id: 14, rot_correction: 0.0,
  vert_correction: -0.017453292519943295, vert_offset_correction: 0.0}
- {dist_correction: 0.0, dist_correction_x: 0.0, dist_correction_y: 0.0, focal_distance: 0.0,
  focal_slope: 0.0, horiz_offset_correction: 0.0, laser_id: 15, rot_correction: 0.0,
  vert_correction: 0.2617993877991494, vert_offset_correction: 0.0}
num_lasers: 16
distance_resolution: 0.002`

Anybody, please suggest fixing this issue. ? Thanks in Advance.

**Comment by msemtd** [comment]
It may be worth applying the vert_offset_correction values mentioned in #190 

How does your scanner data look in VeloView?

**Comment by pavankumarbn** [comment]
@msemtd Thank you for your reply. I will try to apply vert_offset_correction.

**Comment by ajay1606** [comment]
@pavankumarbn , It seems to be a problem with the calibration file (.yaml) .Is that calibration file is default one?

**Comment by pavankumarbn** [comment]
@ajay1606 Thanks for the reply. Yes, it is default one given with Velodyne Driver.

**Comment by JWhitleyAStuff** [comment]
@ajay1606 - There should be an XML calibration file provided with every sensor from Velodyne. You can convert this XML file to a YAML file with the utility `velodyne_pointcloud/scripts/gen_calibration.py`.

**Comment by pavankumarbn** [comment]
@msemtd @ajay1606 @JWhitleyAStuff Thank you all for your valuable suggestions. The reason for this problem is FOV restriction as mentioned by the Velodyne Tech Support Team that current Velodyne ROS drivers don't support FOV restriction.

**Comment by JWhitleyAStuff** [comment]
@pavankumarbn - Please check out the cut_angle parameter on the driver. This is an in-software way to restrict the field of view. I'm not sure it will cover what you're looking for (it looks like it only starts at Y and goes around counter-clockwise) but it might help. I'm sorry the driver doesn't support this feature at this time but we might be able to do so in the ROS2 version or after organized cloud support is added.

**Comment by pavankumarbn** [comment]
@JWhitleyAStuff Sure I will check! Thank you very much.

**Comment by AaronWaxson** [comment]
Which driver can use with Puck Lite, I use velodyne_puck but it didn't work with Puck Lite. How should I do ?

**Comment by nshahrestani** [comment]
@JWhitleyWork Is restricting the FOV using the velodyne GUI still now supported?

**Comment by JWhitleyWork** [comment]
@nshahrestani Please do not bump old threads. If you have a question that has not been answered recently, please create a new issue or ask on [ROS Answers](https://answers.ros.org/).
