### ISSUE TITLE
sudo usage in vdump

### ISSUE THREAD

**Issue by andersfischernielsen** [ros-drivers/velodyne#206]
`velodyne/velodyne_driver/src/vdump` fails to run on a ROS container in docker.
`sudo` is unavailable in the docker container (the default user is already super user).

**Comment by JWhitleyAStuff** [comment]
@andersfischernielsen - Please check out the maint/vdump_as_root branch and see if the vdump script works in your Docker container.

**Comment by JWhitleyAStuff** [comment]
@andersfischernielsen - ping

**Comment by andersfischernielsen** [comment]
Sorry for the late answer. Everything's good now. Thanks! 👍

**Comment by JWhitleyAStuff** [comment]
Awesome. Fixed by #212.
