### ISSUE TITLE
velodyne_driver displays ellipse of laser beams instead of circle

### ISSUE THREAD

**Issue by tobiasneumann** [ros-drivers/velodyne#21]
Hello, we are using the Velodyne HDL-64E S2 with ROS Hydro for indoor mapping. During this we saw, that the ROS.driver for the Velodyne creates Pointclouds where the Laser-beams are in an ellipse instead of a cicle.

In detail described here(also with bagfiles): http://answers.ros.org/question/124641/velodyne_driver-displays-ellipse-of-laser-beams-instead-of-circle/

ROS-driver: http://robotics.fh-aachen.de/pictures/Screenshot%202014-01-30%2023.29.24.png
PCL-driver: http://robotics.fh-aachen.de/pictures/Screenshot%202014-01-30%2023.31.05.png

**Comment by jack-oquin** [comment]
Is it possible to re-run these tests using the current ``master`` and verify whether corrections in the point coordinate computations have fixed it?

**Comment by jack-oquin** [comment]
Closing, since there has been no response.
