### ISSUE TITLE
Non-eth0 Interface

### ISSUE THREAD

**Issue by Engietoday** [ros-drivers/velodyne#215]
Do I need to specify which NIC card the Lidar is connected to? My interface name is eno2 and I'm not able to get any point readings from a 32C.

**Comment by JWhitleyAStuff** [comment]
@Engietoday - You do not need to specify the interface but you must specify the IP address. Make sure that you can ping the IP address from a terminal and visit the sensor's IP address in a browser for configuration. If you can, make sure that it is configured to use 2368 as the data port. If these are correct, make sure you are setting the IP address in the launch file or passing it in like:

    roslaunch velodyne_pointcloud VLP-32C_points.launch device_ip:=192.168.1.201
