### ISSUE TITLE
Potential Depth-image creation

### ISSUE THREAD

**Issue by Gariben** [ros-drivers/velodyne#26]
I would like to see if I could create add the ability to create a depth image to the velodyne stack. I have a theoretical approach lined out:

(from my ros answers post)

I think if I can get the 'rotation' value from the 'row_block_t' (from rawdata.h) and then the 'laser_number' values (from rawdata.cc), I can make a matrix of size ROTATION_MAX_UNITS by SCANS_PER_BLOCK and then store the depth to each pixel (raw->blocks[i].rotation, j). However, I'm kind of unsure on how to access the values I need. I have the velodyne package in my workspace and the rawdata.cc, but I don't know how to use that information.

**Comment by TobiasCy** [comment]
Is the external Project public? I would like to test this approach.

**Comment by jack-oquin** [comment]
I doubt it, but you'd need to contact @Gariben to find out.

**Comment by lschaupp** [comment]
@Gariben i would be interested into your approach. Could  you pm me?

**Comment by FedericoPicetti** [comment]
Hello @Gariben, I'm interested in your approach too. Can we get in contact? Thank you!
