### ISSUE TITLE
ROS 2 Dashing improvement: Rename the node names and file names to be consistent

### ISSUE THREAD

**Issue by clalancette** [ros-drivers/velodyne#264]
RIght now, the node names aren't consistent (some have a "_node" suffix and some don't, some have a "velodyne_" prefix and some don't), and the file names don't necessarily match the node names.  Change all of this to be more consistent.

**Comment by JWhitleyAStuff** [comment]
@clalancette - Would you consider this to be complete by #254?

**Comment by clalancette** [comment]
> @clalancette - Would you consider this to be complete by #254?

Not quite.  I renamed the node names as seen by ROS, but I totally forgot to rename the binaries themselves.  So I'd leave this open for now (I may have some time to complete this later this week).

**Comment by clalancette** [comment]
Actually, never mind, I think this is good now, so I'll close this out.  Thanks!
