### ISSUE TITLE
vlp 16

### ISSUE THREAD

**Issue by kalai86** [ros-drivers/velodyne#273]
hi,
i am using VLP-16 velodyne sensor.
 i try your code is it separate the ground plane and  detect the object ? 
i am using  jetson TX1 nad TX2 board ,is it enough for run the code

thanks
kalai

**Comment by JWhitleyAStuff** [comment]
@kalai86 - The driver here does not do any data processing (such as separating the ground plane and objects). A Jetson TX2 should be fine to run this with a VLP-16.
