### ISSUE TITLE
velodyne_packets topic

### ISSUE THREAD

**Issue by omrirz** [ros-drivers/velodyne#278]
**Please complete the following information:**
 - OS and Version: Ubuntu 16.04
 - ROS Version: Kinetic
 - Built from Source or Downloaded from Official Repository:
 - Version: 16bc0c3

**Describe the bug**
There is a topic namde "velodyne_packets" which is used by the nodelet_manager.
The problem is that if i try to spin multiple lidars they all use this exact same name and there is a collision of data.
A simple solution is to use namespaces but i think it's not so elegant.

**To Reproduce**
1.run roslaunch velodyne_pointcloud 32e_points.launch frame_id:="some_name"
2.run roslaunch velodyne_pointcloud 32e_points.launch frame_id:="some_other_name"
2. run rosrun rqt_graph rqt_graph
3. See that both "some_name" and "some_other_name" publish and subscribe to the same topic "/velodyne_packets"

**Expected behavior**
They should use different name for this internal topic.

**Comment by JWhitleyAStuff** [comment]
@omrirz - The standard practice for handling this is to use namespaces. This is true for all drivers, not just the Velodyne. There are two methods for doing this:

1. From the terminal, you can pass the environment variable ROS_NAMESPACE like this:

>     ROS_NAMESPACE=velodyne1 roslaunch velodyne_pointcloud 32e_points.launch frame_id:="some_name"
>     ROS_NAMESPACE=velodyne2 roslaunch velodyne_pointcloud 32e_points.launch frame_id:="some_other_name"

2. You can create your own launch file (recommended) which uses the `ns` attribute and includes the 32e launch file:

>     <include file="$(find velodyne_pointcloud)/launch/32e_points.launch" ns="velodyne1">
>       <arg name="frame_id" value="some_name"/>
>     </include>
>     <include file="$(find velodyne_pointcloud)/launch/32e_points.launch" ns="velodyne2">
>       <arg name="frame_id" value="some_other_name"/>
>     </include>
