### ISSUE TITLE
ROS2 dashing VLP16 sensor_msgs::msg::PointCloud2 msg's row_step is always 0

### ISSUE THREAD

**Issue by jdclzl** [ros-drivers/velodyne#279]
row_step of  msg comeout of the driver with type sensor_msgs::msg::PointCloud2 is always zero,which cause error after pcl_conversion's fromRosMsg or toRosMsg function.
I add" msg->row_step = msg->data.size() / msg->height;" and problem solved.

**Comment by clalancette** [comment]
This should be fixed by #291, so I'll close this out.  Feel free to reopen if you are still having problems with it.
