### ISSUE TITLE
how to get vertical beam angle for each rings of velodyne lidar

### ISSUE THREAD

**Issue by ajay1606** [ros-drivers/velodyne#282]
Hello all, 

I am using a Velodyne 64 SE model lidar sensor, for some algorithm implementation, am looking for the vertical angle of each ring. 

Although I can get that from the 3D coordinates, because of some obstacles in the environment, its very difficult to get the consistent vertical angle of the laser beam.

Is there any way that I can get actual vertical beam angle in the Velodyne 64 sensor.

Your response greatly appreciated.

Regards,
Ajay

**Comment by JWhitleyAStuff** [comment]
@ajay1606 - The lasers are evenly spaced between -26.9 degrees and +2.0 degrees (approximately 0.4203125 degrees apart). You should be able to calculate the angle of each beam using these data. There are very minor offsets for each sensor but they are provided in the .yaml configuration file that Velodyne provides with the sensor. Please let me know if you have any other questions. Thanks.

**Comment by JWhitleyAStuff** [comment]
Correction: I guess it depends on exactly which model you have. Here are the specifications for the S2, which is slightly different than the SE: https://velodynelidar.com/lidar/products/brochure/HDL-64E%20S2%20datasheet_2010_lowres.pdf

**Comment by ajay1606** [comment]
@JWhitleyAStuff Thank you so much for quick response as always, So **(-24.8 deg)** corresponds to the **ring 0**  and t+2 deg corresponds to the ring 63 in the **<velodyne_pointcloud::PointsXYZIR>** .

Thanks
