### ISSUE TITLE
angle overflow

### ISSUE THREAD

**Issue by he-guo** [ros-drivers/velodyne#294]
**Please complete the following information:**
 - OS and Version: [e.g. Ubuntu 16.04]
 - ROS Version: [e.g. Kinetic]
 - Built from Source or Downloaded from Official Repository:
 - Version: [if from repository, give version from `sudo dpkg -s ros-$ROS_VERSION-velodyne`, if from source, give commit hash]

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional context**
i also have this problem,when I add this topic in rviz, this warning is only available at this time,have you solved it?thinks.

![velodyne drive error](https://user-images.githubusercontent.com/54622758/67354632-1a78ea00-f588-11e9-85ef-dd7d522409bc.png)

**Comment by JWhitleyAStuff** [comment]
Tracking in #275.
