### ISSUE TITLE
Xcoordinate equation seems wrong in rawdata.cc

### ISSUE THREAD

**Issue by evolutionsdisaster** [ros-drivers/velodyne#31]
Hi, 

I  was going through the velodyne/rawdata.cc code and felt like line 199 is wrong(dint look right) and it doesnt match with user manual code provided by the velodyne company.

X coordinate should have been xyDistance*sinRotAngle - hoffsetCorr*cosRotAngle.
Currently its + hoffsetCorr*cosRotAngle.

Please correct me if I am wrong. 

Thankyou, 
~Faiz

**Comment by etake** [comment]
I am using Velodyne HDL64S2  with velodyne_pointcloud node.
I had same horizontal offset problems.

current line 211 in rawdata.c is (maybe, this is same line )
 x = xy_distance * sin_rot_angle + horiz_offset * cos_rot_angle;
and measured result is
![before](https://cloud.githubusercontent.com/assets/10028069/7215200/97707c30-e606-11e4-8d4f-8e7a4a9d08c9.png)
 (sensor: HDL64-S2, target: 50cm circle plate)
In the figure, the circle is blurred.

change the line into 
 x = xy_distance * sin_rot_angle - horiz_offset * cos_rot_angle;
and the measured result is
![after](https://cloud.githubusercontent.com/assets/10028069/7215204/e1c956a8-e606-11e4-9a0a-8d17793f7142.png)

I have not trace all formula of this code. 
But the result is better.

Thank you.

**Comment by jack-oquin** [comment]
Thanks! That is very helpful. 

I have not been actively working on this driver lately. I would accept a pull request with the fix you tried.

**Comment by snehaljain018** [comment]
I think this issue should be closed, as the bug seems to be solved by correcting the error in formula.
