### ISSUE TITLE
hi, I find there are two calibration '.yaml' file for VLP16 in velodyne_pointcloud/params. which is the correct file? and what is the difference between them? Thanks.

### ISSUE THREAD

**Issue by Zhang-Qinghui** [ros-drivers/velodyne#312]
**Is your feature request related to a problem? Please describe.
question
**Describe the solution you'd like**
I want some explantion.
**Describe alternatives you've considered**

**Additional context**

**Comment by JWhitleyAStuff** [comment]
1. In the future, please fill out the questions in the template for new issues.
2. One is for the VLP-16 (VLP16db.yaml) and one is for the VLP-16 Hi-Res (VLP16_hires_db.yaml). The Hi-res version has tighter vertical spacing.

**Comment by Zhang-Qinghui** [comment]
Thanks for your reply. I will use the template for new issues in the future.
