### ISSUE TITLE
How to get the XYZ data of the Velodyne point cloud？

### ISSUE THREAD

**Issue by liu978079474** [ros-drivers/velodyne#314]
How to get the XYZ data of the Velodyne point cloud？

**Comment by liu978079474** [comment]
In ROS, subscribe to the topic of Velodyne_piont and get the parsed data, but I don't know which one. So I want to resubscribe to a topic to get Velodyne's XYZ data and display it.

**Comment by JWhitleyAStuff** [comment]
@liu978079474 The point cloud data are published to `/points_raw` by default. You can display this topic in RVIZ as well. If this does not answer your question, please re-open.
