### ISSUE TITLE
VLP-32C max_range is 130m, while the sensor can output 200m

### ISSUE THREAD

**Issue by kaarta-SHanna** [ros-drivers/velodyne#315]
**Please complete the following information:**
 - OS and Version: Ubuntu 16.04
 - ROS Version: Kinetic
 - Built from Source or Downloaded from Official Repository:
 - Version: [if from repository, give version from `sudo dpkg -s ros-$ROS_VERSION-velodyne`, if from source, give commit hash]

**Describe the bug**
https://github.com/ros-drivers/velodyne/blob/master/velodyne_pointcloud/launch/VLP-32C_points.launch#L11
&
https://velodynelidar.com/vlp-32c.html
The VLP-32C launch file has a max_range set to 130, while the sensor can produce 200m range outputs

**To Reproduce**

**Expected behavior**
Change to 130m

**Additional context**
I'll setup a PR when I get a chance

**Comment by JWhitleyAStuff** [comment]
Closed by #323
