### ISSUE TITLE
Number of packets published per message is not exactly a revolution if "npackets" set to default

### ISSUE THREAD

**Issue by ddillenberger** [ros-drivers/velodyne#33]
Hello@all,

we would like to submit a patch (velodyne_driver/driver.cc) which would cut the packet stream in a better way, so that a single revolution always starts/ends at a specific angle (for example while the LIDAR points to the robot).
There are two reasons for that:
First is that we've never seen a Velodyne LIDAR (we work with multiple 64E S2 and 32E models) whose rotation speed is very stable. Especially the  64E S2 models tend to be much slower than set when the enviroment temperature is low (10Hz measured instead of 15Hz set at 5-10°C). And our 32E models are varying between 9 and 11 Hz (indoor, same temperature), but all are set to 10Hz. Along with the varying rotation speed the number of packets per revolution vary a lot. This leads in the end to overlapping or missing sectors in the published pointclouds. (It actually looks quite cool in RViz :-D, but it can be a problem for some algorithms)
Second reason is that start and end of a revolution are an discontinuous area (if the robot moves), which can lead to wrong algorithm results in this area. With setting "the cut" to a specific angle you can move this area to an angle where it doesn't matter if you get wrong results.

Any objections?

Best regards
Denis

**Comment by JWhitleyAStuff** [comment]
This was added with #126.
