### ISSUE TITLE
Future development plans

### ISSUE THREAD

**Issue by YoshuaNava** [ros-drivers/velodyne#339]
Do you have further plans for the development of this driver? As further integration of ROS2, multiple return functionality, and adding new features.

For example, an interesting feature provided by Ouster is their [img_node](https://github.com/ouster-lidar/ouster_example/blob/master/ouster_ros/src/img_node.cpp).

**Comment by JWhitleyWork** [comment]
@YoshuaNava This repository is community-developed. I'm just a lowly maintainer and squeeze in any effort that I can make time for. I also don't have access to physical hardware for testing anymore so I can't make large feature changes without a 3rd-party tester. Please feel free to add any functionality you would like to see in a PR and I'll be happy to review it (and rely on others for testing).
