### ISSUE TITLE
Release for Noetic

### ISSUE THREAD

**Issue by Timple** [ros-drivers/velodyne#343]
**Is your feature request related to a problem? Please describe.**
The [call for testing](https://discourse.ros.org/t/ros-noetic-call-for-testing) revealed that these packages are not yet released for noetic. 

**Describe the solution you'd like**
Release for noetic

**Describe alternatives you've considered**
Building from source: also works, but less efficient if lots of people have to do that.

**Additional context**
I realise that noetic has been mentioned [here](https://github.com/ros-drivers/velodyne/pull/335#issuecomment-608110519) and [here](https://github.com/ros-drivers/velodyne/issues/340). But those issues are not created for a noetic release specific, although they might be blocking or give additional insights.
So I thought I'd create a placeholder issue.

**Comment by JWhitleyWork** [comment]
@Timple Very sorry this took so long. There were a few issues that needed to be resolved before I could make the release. PR is now in for release. https://github.com/ros/rosdistro/pull/25737
