### ISSUE TITLE
E: Unable to locate package ros-noetic-velodyne-msgs

### ISSUE THREAD

**Issue by ankitdhall** [ros-drivers/velodyne#354]
**System:**
 - Ubuntu 20.04
 - ROS Noetic
 - Built from Source or Downloaded from Official Repository: NA
 - Version: NA

**Describe the bug**
Unable to install `ros-noetic-velodyne-msgs` and `ros-noetic-velodyne-pointcloud`.
Receive the following error on the terminal:
```
E: Unable to locate package ros-noetic-velodyne-msgs
E: Unable to locate package ros-noetic-velodyne-pointcloud

ERROR: the following rosdeps failed to install
apt: command [sudo -H apt-get install -y ros-noetic-velodyne-msgs] failed
apt: command [sudo -H apt-get install -y ros-noetic-velodyne-pointcloud] failed
apt: Failed to detect successful installation of [ros-noetic-velodyne-msgs]
apt: Failed to detect successful installation of [ros-noetic-velodyne-pointcloud]
```

**To Reproduce**
Reproduced on the GitHub workflow [here](https://github.com/ankitdhall/lidar_camera_calibration/blob/05ef6cc7ead1aca1ae3fc21732ad09f99cff3003/.github/workflows/noetic.yml)

**Expected behavior**
Should be able to install packages. Works well for ROS Kinetic and ROS Melodic but fails for ROS Noetic.

**Additional context**
![image](https://user-images.githubusercontent.com/8938083/87792656-7e44f080-c844-11ea-9509-09b5258feeb3.png)

**Comment by JWhitleyWork** [comment]
@ankitdhall The packages have been released but haven't been sync'd to the build farm yet. See status here: http://repositories.ros.org/status_page/ros_noetic_default.html?q=velodyne. The sync is currently pending so it shouldn't be long. See sync status here: https://discourse.ros.org/t/preparing-for-noetic-sync-2020-07-17/15434
