### ISSUE TITLE
Is version 2.1.0 compatible with version 1.6.0?

### ISSUE THREAD

**Issue by WysokiStudent** [ros-drivers/velodyne#358]
In a nutshell the question is "Is this project using [semantic versioning](https://semver.org/)?" If so what are the breaking changes that caused the jump from 1.6.0 to 2.1.0.

**Comment by JWhitleyWork** [comment]
@WysokiStudent We do use Symantic Versioning and the difference between 1.6.0 and 2.1.0 is that the 2.x.x line is for ROS 2 while the 1.x.x line is for ROS 1. Please let me know if you have any other questions.
