### ISSUE TITLE
pointcloud topic publish frequency is very low at ros2 dashing on nvidia xavier with VLP16

### ISSUE THREAD

**Issue by 849631323** [ros-drivers/velodyne#367]
**Please complete the following information:**
 - OS and Version: [e.g. Ubuntu 18.04]
 - ROS Version: [e.g. Dashing]
 - Built from Source or Downloaded from Official Repository:
 - Version: [if from repository, give version from `sudo dpkg -s ros-$ROS_VERSION-velodyne`, if from source, give commit hash]

**Describe the bug**
topic /velodyne_points publish frequency is very low at ros2 dashing on nvidia xavier with VLP16.
but when use ros-melodic it give out frequency is almost 10.

**To Reproduce**
1. git clone https://github.com/ros-drivers/velodyne.git --branch=dashing-devel
2. cd velodyne && colcon build
3. source install/setup.bash
4. ros2 launch velodyne velodyne-all-nodes-VLP16.launch.py
open another terminal :
$ ros2 topic hz /velodyne_points
it give out freqency is less than 7,most time even less than 5
 
**Expected behavior**
give out publish freqency almost 10

**Additional context**

**Comment by JWhitleyWork** [comment]
It looks like this is a DDS problem. Closing.
