### ISSUE TITLE
How can I use Puck Lite in ROS？

### ISSUE THREAD

**Issue by AaronWaxson** [ros-drivers/velodyne#371]
**Is your feature request related to a problem? Please describe.**
I need use Puck Llite In ROS.

**Describe the solution you'd like**
Tell which ros driver can help me, or how to start Puck Lite in Ubuntu with C++ or python.

**Describe alternatives you've considered**
Hope you can response my request asap.  Thanks a lot.
**Additional context**

**Comment by JWhitleyWork** [comment]
The Puck Lite is identical to the standard Puck (VLP-16) other than weight. You can use the VLP-16 launch file.
