### ISSUE TITLE
Any possibility to drive three Lidars in a single node with only one thread?

### ISSUE THREAD

**Issue by zclzzx** [ros-drivers/velodyne#380]
Is there any possibility to use only one thread in a velodyne ros driver node to receive packet from three Lidars, Rather than three driver nodes or three threads in one driver node.

Now I want to modify velodyne ros driver to improve Lidar localization performance. However, the output scan is always incomplete when I use async_receive_from function in boost::asio to asynchronously receive the data from three velodyne Lidars. I am looking forward to getting any suggestion.

**Comment by JWhitleyWork** [comment]
Unfortunately, this is not possible without a signfiicant re-write. The node can only bind to a single UDP port with the current architecture and the `velodyne_driver` isn't written to separate packets coming from multiple Velodynes on a single port.
