### ISSUE TITLE
Unable to access web server and failed to poll device

### ISSUE THREAD

**Issue by BeomBeom2** [ros-drivers/velodyne#407]
**Please complete the following information:**
 - OS and Version: [e.g. Ubuntu 20.04]
 - ROS Version: [e.g. noetic]
 - Built from Source or Downloaded from Official Repository:
 - Version: [if from repository, give version from `sudo dpkg -s ros-$ROS_VERSION-velodyne`, if from source, give commit hash]

**Describe the bug**

I set the 192.168.1.201 IP provided by VLP32C, but I cannot connect to the web server.

This is the IP configuration you have set
![Ip config](https://user-images.githubusercontent.com/62642155/119839254-fee17c80-bf3e-11eb-8ecd-3d98ff5aeb69.png)

IP packet with wireshark
![wireshark](https://user-images.githubusercontent.com/62642155/119839639-46680880-bf3f-11eb-951a-b6d646feb17e.png)

rostopic list
![topiclist](https://user-images.githubusercontent.com/62642155/119841710-0144d600-bf41-11eb-9861-2767d0f220f7.png)

**Expected behavior**

roslaunch velodyne_pointcloud VLP-32C_points.launch
... logging to /home/ubuntu/.ros/log/64a90466-bef4-11eb-97f2-89ebe3c6c445/roslaunch-ubuntu-5678.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:42381/

SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.15.11
 * /velodyne_nodelet_manager_driver/cut_angle: -0.01
 * /velodyne_nodelet_manager_driver/device_ip:
 * /velodyne_nodelet_manager_driver/frame_id: velodyne
 * /velodyne_nodelet_manager_driver/gps_time: False
 * /velodyne_nodelet_manager_driver/model: 32C
 * /velodyne_nodelet_manager_driver/pcap:
 * /velodyne_nodelet_manager_driver/pcap_time: False
 * /velodyne_nodelet_manager_driver/port: 2368
 * /velodyne_nodelet_manager_driver/read_fast: False
 * /velodyne_nodelet_manager_driver/read_once: False
 * /velodyne_nodelet_manager_driver/repeat_delay: 0.0
 * /velodyne_nodelet_manager_driver/rpm: 600.0
 * /velodyne_nodelet_manager_driver/timestamp_first_packet: False
 * /velodyne_nodelet_manager_laserscan/resolution: 0.007
 * /velodyne_nodelet_manager_laserscan/ring: -1
 * /velodyne_nodelet_manager_transform/calibration: /home/ubuntu/catk...
 * /velodyne_nodelet_manager_transform/fixed_frame:
 * /velodyne_nodelet_manager_transform/max_range: 200.0
 * /velodyne_nodelet_manager_transform/min_range: 0.4
 * /velodyne_nodelet_manager_transform/model: 32C
 * /velodyne_nodelet_manager_transform/organize_cloud: False
 * /velodyne_nodelet_manager_transform/target_frame:

NODES
  /
    velodyne_nodelet_manager (nodelet/nodelet)
    velodyne_nodelet_manager_driver (nodelet/nodelet)
    velodyne_nodelet_manager_laserscan (nodelet/nodelet)
    velodyne_nodelet_manager_transform (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [5686]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 64a90466-bef4-11eb-97f2-89ebe3c6c445
process[rosout-1]: started with pid [5696]
started core service [/rosout]
process[velodyne_nodelet_manager-2]: started with pid [5699]
process[velodyne_nodelet_manager_driver-3]: started with pid [5700]
process[velodyne_nodelet_manager_transform-4]: started with pid [5701]
process[velodyne_nodelet_manager_laserscan-5]: started with pid [5702]
[ INFO] [1622124248.344524520]: Initializing nodelet with 4 worker threads.
[ INFO] [1622124248.635680025]: Velodyne VLP-32C rotating at 600 RPM
[ INFO] [1622124248.637555231]: publishing 151 packets per scan
[ INFO] [1622124248.646196229]: Cut at specific angle feature deactivated.
[ INFO] [1622124248.669168454]: Reconfigure Request
[ INFO] [1622124248.674812201]: expected frequency: 9.980 (Hz)
[ INFO] [1622124248.685950826]: Opening UDP socket: port 2368
0.000 0.000 2.304 2.304 4.608 4.608 6.912 6.912 9.216 9.216 11.520 11.520 13.824 13.824 16.128 16.128 18.432 18.432 20.736 20.736 23.040 23.040 25.344 25.344 27.648 27.648 29.952 29.952 32.256 32.256 34.560 34.560
55.296 55.296 57.600 57.600 59.904 59.904 62.208 62.208 64.512 64.512 66.816 66.816 69.120 69.120 71.424 71.424 73.728 73.728 76.032 76.032 78.336 78.336 80.640 80.640 82.944 82.944 85.248 85.248 87.552 87.552 89.856 89.856
110.592 110.592 112.896 112.896 115.200 115.200 117.504 117.504 119.808 119.808 122.112 122.112 124.416 124.416 126.720 126.720 129.024 129.024 131.328 131.328 133.632 133.632 135.936 135.936 138.240 138.240 140.544 140.544 142.848 142.848 145.152 145.152
165.888 165.888 168.192 168.192 170.496 170.496 172.800 172.800 175.104 175.104 177.408 177.408 179.712 179.712 182.016 182.016 184.320 184.320 186.624 186.624 188.928 188.928 191.232 191.232 193.536 193.536 195.840 195.840 198.144 198.144 200.448 200.448
221.184 221.184 223.488 223.488 225.792 225.792 228.096 228.096 230.400 230.400 232.704 232.704 235.008 235.008 237.312 237.312 239.616 239.616 241.920 241.920 244.224 244.224 246.528 246.528 248.832 248.832 251.136 251.136 253.440 253.440 255.744 255.744
276.480 276.480 278.784 278.784 281.088 281.088 283.392 283.392 285.696 285.696 288.000 288.000 290.304 290.304 292.608 292.608 294.912 294.912 297.216 297.216 299.520 299.520 301.824 301.824 304.128 304.128 306.432 306.432 308.736 308.736 311.040 311.040
331.776 331.776 334.080 334.080 336.384 336.384 338.688 338.688 340.992 340.992 343.296 343.296 345.600 345.600 347.904 347.904 350.208 350.208 352.512 352.512 354.816 354.816 357.120 357.120 359.424 359.424 361.728 361.728 364.032 364.032 366.336 366.336
387.072 387.072 389.376 389.376 391.680 391.680 393.984 393.984 396.288 396.288 398.592 398.592 400.896 400.896 403.200 403.200 405.504 405.504 407.808 407.808 410.112 410.112 412.416 412.416 414.720 414.720 417.024 417.024 419.328 419.328 421.632 421.632
442.368 442.368 444.672 444.672 446.976 446.976 449.280 449.280 451.584 451.584 453.888 453.888 456.192 456.192 458.496 458.496 460.800 460.800 463.104 463.104 465.408 465.408 467.712 467.712 470.016 470.016 472.320 472.320 474.624 474.624 476.928 476.928
497.664 497.664 499.968 499.968 502.272 502.272 504.576 504.576 506.880 506.880 509.184 509.184 511.488 511.488 513.792 513.792 516.096 516.096 518.400 518.400 520.704 520.704 523.008 523.008 525.312 525.312 527.616 527.616 529.920 529.920 532.224 532.224
552.960 552.960 555.264 555.264 557.568 557.568 559.872 559.872 562.176 562.176 564.480 564.480 566.784 566.784 569.088 569.088 571.392 571.392 573.696 573.696 576.000 576.000 578.304 578.304 580.608 580.608 582.912 582.912 585.216 585.216 587.520 587.520
608.256 608.256 610.560 610.560 612.864 612.864 615.168 615.168 617.472 617.472 619.776 619.776 622.080 622.080 624.384 624.384 626.688 626.688 628.992 628.992 631.296 631.296 633.600 633.600 635.904 635.904 638.208 638.208 640.512 640.512 642.816 642.816
[ INFO] [1622124248.806957340]: correction angles: /home/ubuntu/catkin_ws/src/velodyne/velodyne_pointcloud/params/VeloView-VLP-32C.yaml
[ INFO] [1622124248.824721555]: laser_ring[ 0] =  0, angle = -0.436332
[ INFO] [1622124248.825279309]: laser_ring[ 3] =  1, angle = -0.272952
[ INFO] [1622124248.825773212]: laser_ring[ 4] =  2, angle = -0.197397
[ INFO] [1622124248.825988858]: laser_ring[ 7] =  3, angle = -0.154339
[ INFO] [1622124248.826167857]: laser_ring[ 8] =  4, angle = -0.126606
[ INFO] [1622124248.826357448]: laser_ring[11] =  5, angle = -0.107303
[ INFO] [1622124248.826561039]: laser_ring[12] =  6, angle = -0.093078
[ INFO] [1622124248.826755296]: laser_ring[16] =  7, angle = -0.081455
[ INFO] [1622124248.826934758]: laser_ring[15] =  8, angle = -0.069813
[ INFO] [1622124248.827113756]: laser_ring[19] =  9, angle = -0.064001
[ INFO] [1622124248.827448920]: laser_ring[20] = 10, angle = -0.058172
[ INFO] [1622124248.827654288]: laser_ring[24] = 11, angle = -0.052360
[ INFO] [1622124248.827837120]: laser_ring[23] = 12, angle = -0.046548
[ INFO] [1622124248.828017767]: laser_ring[27] = 13, angle = -0.040719
[ INFO] [1622124248.828190506]: laser_ring[28] = 14, angle = -0.034907
[ INFO] [1622124248.828365338]: laser_ring[ 2] = 15, angle = -0.029095
[ INFO] [1622124248.828541781]: laser_ring[31] = 16, angle = -0.023265
[ INFO] [1622124248.828720723]: laser_ring[ 1] = 17, angle = -0.017453
[ INFO] [1622124248.828946518]: laser_ring[ 6] = 18, angle = -0.011641
[ INFO] [1622124248.829132757]: laser_ring[10] = 19, angle = -0.005812
[ INFO] [1622124248.829321774]: laser_ring[ 5] = 20, angle = +0.000000
[ INFO] [1622124248.829505142]: laser_ring[ 9] = 21, angle = +0.005812
[ INFO] [1622124248.829689604]: laser_ring[14] = 22, angle = +0.011641
[ INFO] [1622124248.829873454]: laser_ring[18] = 23, angle = +0.017453
[ INFO] [1622124248.830141655]: laser_ring[13] = 24, angle = +0.023265
[ INFO] [1622124248.830373302]: laser_ring[17] = 25, angle = +0.029095
[ INFO] [1622124248.830572855]: laser_ring[22] = 26, angle = +0.040719
[ INFO] [1622124248.830756280]: laser_ring[21] = 27, angle = +0.058172
[ INFO] [1622124248.830933593]: laser_ring[26] = 28, angle = +0.081455
[ INFO] [1622124248.831108943]: laser_ring[25] = 29, angle = +0.122173
[ INFO] [1622124248.831368682]: laser_ring[30] = 30, angle = +0.180345
[ INFO] [1622124248.831555939]: laser_ring[29] = 31, angle = +0.261799
[ INFO] [1622124248.832998575]: Number of lasers: 32.
[ WARN] [1622124248.836539007]: No Azimuth Cache configured for model 32C
[ INFO] [1622124248.884229478]: Reconfigure request.
[ INFO] [1622124248.884431939]: Target frame ID now:
[ INFO] [1622124248.884540142]: Fixed frame ID now:
[ INFO] [1622124248.884814158]: Initialized container with min_range: 0.4, max_range: 200, target_frame: , fixed_frame: , init_width: 0, init_height: 1, is_dense: 1, scans_per_packet: 384
[ WARN] [1622124249.695243653]: Velodyne poll() timeout
[ERROR] [1622124249.695719001]: DriverNodelet::devicePoll - Failed to poll device.
[ WARN] [1622124250.697415284]: Velodyne poll() timeout
[ERROR] [1622124250.697665615]: DriverNodelet::devicePoll - Failed to poll device.
[ WARN] [1622124251.699328676]: Velodyne poll() timeout
[ERROR] [1622124251.699534100]: DriverNodelet::devicePoll - Failed to poll device.
[ WARN] [1622124252.700902924]: Velodyne poll() timeout
[ERROR] [1622124252.701126940]: DriverNodelet::devicePoll - Failed to poll device.

**Comment by JWhitleyWork** [comment]
@BeomBeom2 You are experiencing this issue because the default IP address _of the sensor_ is 192.168.1.201. The IP address of your computer should be in the same subnet but be a different IP - for example, 192.168.1.50.

Additionally, it looks like your Wifi (`wlan0`) also uses this subnet and you can not have two interfaces on the same computer using the same subnet. Change your `eth0` IP address and disable your wifi and you should be able to connect. FYI - this is out of the scope of this repository since this is a network issue and not an issue with the driver so I'm closing the issue.
