### ISSUE TITLE
Catkin_make Error

### ISSUE THREAD

**Issue by ManChrys** [ros-drivers/velodyne#412]
- OS and Version: 18.04
 - ROS Version: melodic

Hello guys,

I tried to install velodyne package following these steps

https://wiki.ros.org/velodyne/Tutorials/Getting%20Started%20with%20the%20HDL-32E

but i have the following error

![Screenshot from 2021-06-23 12-37-03](https://user-images.githubusercontent.com/67521662/123074285-d3f42680-d41f-11eb-97d1-41a7df472d39.png)

Can anyone help me to solve this ? 

Thanks in advance!

**Comment by JWhitleyWork** [comment]
This problem is an issue with other packages in your workspace and is not related to the Velodyne driver. Please ask this question on [ROS Answers](https://answers.ros.org) and you should get an answer quickly.

**Comment by ManChrys** [comment]
ok thank you!
