### ISSUE TITLE
Velodyne poll() timeout

### ISSUE THREAD

**Issue by hxj0316** [ros-drivers/velodyne#416]
Hello, I compiled vlp_driver under ros2, and then I ran the "ros2 run velodyne_driver velodyne_driver_node" command, and the result was as shown in the figure below. I pinged the address of the lidar, and it was able to ping. , I don’t know why there is such a problem, please help me to take a look, thank you.
![2021-07-28 22-31-07 的屏幕截图](https://user-images.githubusercontent.com/66103957/127341458-0cccc372-e685-4d2b-8dc4-4c19dcfe9ced.png)

**Comment by TZECHIN6** [comment]
I am facing the same issue now. LiDAR can be ping and the IP setting should be correct, but still getting poll timeout.

Anyone could help on this? Thanks

**Comment by himhan34** [comment]
I think i saw some reports that dealing ros2 with that file can you search closed repo?

**Comment by TZECHIN6** [comment]
@himhan34 you are right, I can connect the lidar at that time... so I really have no clues why now I only setting up for one lidar and it doesn't work... (the project is new, so I haven't changed any of the code from ros2 branch)

**Comment by himhan34** [comment]
mostly when i used the vlp 16 with ros1 and when i got that message i started from the bottom, 
so i started with the beginning, i installed the wireshark and check the ip of the lidar, and check to see the lidar is properly
connected and sending and getting the right packets try to start at the beginning

**Comment by TZECHIN6** [comment]
thats why I am so frustrated, as I done all of these: IP config, ping test, reset all the hardware & software, wireshark to see package deliver status, as well as using veloview to see the lidar scan. But none of these indicated wheres the problem, except veloview, as it also doesn't show any lidar point as well, but other than that, everything looks reasonable to me. lidar can be pinged, wireshark can see the package sending from correct IP to correct destination IP with UDP package length 1268/1238 I forgot the number, but its corret.

**Comment by TZECHIN6** [comment]
@himhan34  I fix the issue somehow

FYI, https://github.com/ros-drivers/velodyne/issues/505

**Comment by himhan34** [comment]
Its good to hear that . 
Have a nice day 
Best regards
