### ISSUE TITLE
LINK : fatal error LNK1104: cannot open file 'Debug\velodyne_laserscan.lib' 

### ISSUE THREAD

**Issue by lawrenceglewis** [ros-drivers/velodyne#419]
**Please complete the following information:**
 - Windows 10
 - ROS2 foxy
 - building "ros2" branch
 - Version: [if from repository, give version from `sudo dpkg -s ros-$ROS_VERSION-velodyne`, if from source, give commit hash]

**Describe the bug**
I am trying to build and eventually run this package but it wont even build. What is interesting is the fact that the velodyne_laserscan.lib doesn't exist in that file location and I searched the entire C:\ drive for it but it still doesn't exist. I would also to know what needs to use velodyne_laserscan.lib because the error message doesn't really tell me what the file is used for.  Also for your information I tried to use both administrator command promt and I tried building with 
DCMAKE_BUILD_TYPE=Debug. Nothing seems to work.

**To Reproduce**
1.  run comand from comand prompt $ --merge-install --event-handlers console_cohesion+  after setting up environment

**Expected behavior**
I want to see all 6 packages built. 

**Additional context**
velodyne_laserscan.vcxproj -> C:\velodyne_ws\build\velodyne_laserscan\Debug\velodyne_laserscan.dll
LINK : fatal error LNK1104: cannot open file 'Debug\velodyne_laserscan.lib' [C:\velodyne_ws\build\velodyne_laserscan\velodyne_laserscan_node.vcxproj]

**Comment by JWhitleyWork** [comment]
Unfortunately, Windows is not a supported platform for this Velodyne driver. This driver uses Linux-specific libraries to connect to network ports and would require a significant overhaul to change this. You are welcome to create an issue to make this a feature request but we can not offer support on Windows at this time.
