### ISSUE TITLE
Catkin_make error : This workspace contains non-catkin packages in it, and catkin cannot build   a non-homogeneous workspace without isolation.  Try the   'catkin_make_isolated' command instead. Call Stack (most recent call first):   CMakeLists.txt:63 (catkin_workspace)

### ISSUE THREAD

**Issue by raypsaw** [ros-drivers/velodyne#420]
I was trying to install rosserial-arduino. ROS kinetic has previously been installed. After searching how on earth to work with ROS packages, I tried:

cd /src
git clone https://github.com/ros-drivers/rosserial.git
cd
catkin_make
catkin_make install

and got the output:

Base path: /home/robotis/catkin_ws
Source space: /home/robotis/catkin_ws/src
Build space: /home/robotis/catkin_ws/build
Devel space: /home/robotis/catkin_ws/devel
Install space: /home/robotis/catkin_ws/install
Running command: "make cmake_check_build_system" in "/home/robotis/catkin_ws/build"

-- Using CATKIN_DEVEL_PREFIX: /home/robotis/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /home/robotis/catkin_ws/devel;/opt/ros/kinetic
-- This workspace overlays: /home/robotis/catkin_ws/devel;/opt/ros/kinetic
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/robotis/catkin_ws/build/test_results
-- Found gmock sources under '/usr/src/gmock': gmock will be built
-- Found gtest sources under '/usr/src/gmock': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.14
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~ traversing 69 packages in topological order:
-- ~~ - humanoid_navigation (metapackage)
-- ~~ - op3_bringup
-- ~~ - op3_description
-- ~~ - op3_gazebo
-- ~~ - op3_navigation
-- ~~ - op3_web_setting_tool
-- ~~ - robotis_framework (metapackage)
-- ~~ - robotis_op3 (metapackage)
-- ~~ - robotis_op3_common (metapackage)
-- ~~ - robotis_op3_demo (metapackage)
-- ~~ - robotis_op3_msgs (metapackage)
-- ~~ - robotis_op3_tools (metapackage)
-- ~~ - robotis_utility (metapackage)
-- ~~ - rosserial (metapackage)
WARNING: The CMakeLists.txt of the metapackage 'rosserial' contains non standard content. Use the content of the following file instead: /home/robotis/catkin_ws/build/catkin_generated/metapackages/rosserial/CMakeLists.txt
-- ~~ - rosserial_arduino
-- ~~ - rosserial_chibios
-- ~~ - rosserial_mbed
-- ~~ - rosserial_msgs
-- ~~ - rosserial_python
-- ~~ - rosserial_tivac
-- ~~ - rosserial_vex_cortex
-- ~~ - rosserial_vex_v5
-- ~~ - rosserial_xbee
-- ~~ - rosserial_client
-- ~~ - op3_action_module_msgs
-- ~~ - op3_offset_tuner_msgs
-- ~~ - op3_tuning_module_msgs
-- ~~ - op3_walking_module_msgs
-- ~~ - beginner_tutorials
-- ~~ - dynamixel_sdk
-- ~~ - gridmap_2d
-- ~~ - humanoid_planner_2d
-- ~~ - robotis_device
-- ~~ - robotis_framework_common
-- ~~ - robotis_math
-- ~~ - op3_balance_control
-- ~~ - op3_kinematics_dynamics
-- ~~ - ros_madplay_player
-- ~~ - ros_mpg321_player
-- ~~ - op3_offset_tuner_client
-- ~~ - op3_tuner_client
-- ~~ - scilab_optimization
-- ~~ - op3_camera_setting_tool
-- ~~ - rosserial_server
-- ~~ - face_detection
-- ~~ - op3_ball_detector
-- ~~ - op3_online_walking_module_msgs
-- ~~ - robotis_controller_msgs
-- ~~ - op3_action_module
-- ~~ - op3_base_module
-- ~~ - op3_direct_control_module
-- ~~ - op3_head_control_module
-- ~~ - op3_online_walking_module
-- ~~ - op3_read_write_demo
-- ~~ - op3_tuning_module
-- ~~ - op3_walking_module
-- ~~ - open_cr_module
-- ~~ - robotis_controller
-- ~~ - op3_action_editor
-- ~~ - op3_manager
-- ~~ - op3_offset_tuner_server
-- ~~ - footstep_planner
-- ~~ - op3_gui_demo
-- ~~ - op3_localization
-- ~~ - humanoid_localization
-- ~~ - rosserial_embeddedlinux
-- ~~ - rosserial_test
-- ~~ - rosserial_windows
-- ~~ - op3_demo
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkin_workspace.cmake:95 (message):
This workspace contains non-catkin packages in it, and catkin cannot build
a non-homogeneous workspace without isolation. Try the
'catkin_make_isolated' command instead.
Call Stack (most recent call first):
CMakeLists.txt:63 (catkin_workspace)

-- Configuring incomplete, errors occurred!
See also "/home/robotis/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/robotis/catkin_ws/build/CMakeFiles/CMakeError.log".
Makefile:4434: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed

**Comment by JWhitleyWork** [comment]
This is not at all specific to `velodyne`. Please post on [ROS Answers](https://answers.ros.org/)
