### ISSUE TITLE
Incorrect timestamps (!=GPRMC string) while using gps_time = true and PPS

### ISSUE THREAD

**Issue by gabriel-earle** [ros-drivers/velodyne#422]
**Please complete the following information:**
 - OS and Version: Ubuntu 18.04
 - ROS Version: Melodic
 - Built from Source or Downloaded from Official Repository: Built from source
 - Version: melodic-devel commit b809629

**Describe the bug**
Hello, I am getting unexpected timestamps using gps_time = true with GPRMC strings.  I am simulating GPRMC strings each second from a Teensy (Arduino) GPIO, and another pin sends a PPS.  I am monitoring the GPRMC strings and they have the right time.  However, the ROS messages have an timestamp that does not match. It's usually around 20-30 minutes early, but the offset is not constant.

I am finding the error with both a Velodyne VLP-16 and a Velodyne VLP-16 Hi-res.  Please let me know any recommendations I can try for debugging, many thanks.

**To Reproduce**
1. Clone melodic-devel on Ubuntu 18.04
2. Send GPRMC strings and PPS lock to Velodyne VLP-16.
3. Run driver with gps_time = true and launch file pictured below.
4. Inspect the header timestamps.

**Expected behavior**
The velodyne_packets and velodyne_points have header timestamps matching the GPRMC string time/date fields.

**Additional context**
The issue:
![image](https://user-images.githubusercontent.com/54010352/130523443-a7c64378-5c27-4c38-b13d-e57a5167a797.png)
So as I print the GPRMC messages coming from the microcontroller to console, the logging timestamps match (1629754973 = 9:42:53PM GMT Aug 23, 2021).

However, the timestamps from the velodyne_points headers came out ~20 minutes ahead in this case.

My launch file:
![image](https://user-images.githubusercontent.com/54010352/130522648-c5eb19e7-e003-49c1-a95b-912532b3b1fb.png)

My lidar config with PPS lock confirmed:
![image](https://user-images.githubusercontent.com/54010352/130523061-518bf3f0-c23e-4363-a496-70e7411f4bce.png)

My lidar firmware:
![image](https://user-images.githubusercontent.com/54010352/130523882-30586c7a-7e77-45f0-9fb4-4362e37d4deb.png)

**Comment by adthoms** [comment]
@gabriel-earle and others, this was an issue with NMEA scheduling after the PPS signal that was not documented in the VLP16 manual we were using. We have long corrected this problem, and our original issue does not concern the velodyne driver. This issue may be closed.

**Comment by JWhitleyWork** [comment]
Thank you, @adthoms!
