### ISSUE TITLE
Differences between in ros recorded intensity and calibrated reflectivity?

### ISSUE THREAD

**Issue by happengor** [ros-drivers/velodyne#423]
Hello everybody, 

I have a question. Does the intensity in ROS mean the same as  calibrated reflectivity(defined in user manual) ?
What i understand is the intensity represents the reflected infrared reflectance normalized by square distance, while reflectivity ist the property of material, maybe their values are the same, but they are physically different?

Best regards

**Comment by Oyssster** [comment]
> Hello everybody,
> 
> I have a question. Does the intensity in ROS mean the same as calibrated reflectivity(defined in user manual) ?
> What i understand is the intensity represents the reflected infrared reflectance normalized by square distance, while reflectivity ist the property of material, maybe their values are the same, but they are physically different?
> 
> Best regards

I think the reflectivity defined in the user manual is same as the intensity. You can find the result on page 32 in the manual.
