### ISSUE TITLE
Which sensors are supported by this driver? 

### ISSUE THREAD

**Issue by fred-apex-ai** [ros-drivers/velodyne#424]
@JWhitleyWork Do you know which sensors of https://velodynelidar.com/products/ are supported by this driver? Are the solid-state sensors covered as well? 

Thanks!

**Comment by JWhitleyWork** [comment]
Only the spinning lidars - specifically the VLP-16 (Puck), HDL-32E, VLP-32C (Ultra Puck), Puck Lite, HDL-64 (all models), and VLP-128C (Alpha Prime).

**Comment by padhupradheep** [comment]
Does VLP-128C  as support for ROS 2?
