### ISSUE TITLE
ROS2 Foxy communicating with Velodyne VLP16

### ISSUE THREAD

**Issue by aghari19** [ros-drivers/velodyne#431]
Hello, 

I am using Ubuntu 20.04, running ROS2 Foxy and trying to communicate with the Velodyne VLP16. I want to know the the packages I have to run to to see the /scan, /velodyne_points topics on Rviz. Eventually I want to run slam_gmapping on it. My LiDAR is on 192.168.3.200 ip and port 2368

I git cloned [this](https://github.com/ros-drivers/velodyne.git) branch foxy-devel repo into a workspace, sourced it. 

When I run the velodyne_driver package I see this:
![image](https://user-images.githubusercontent.com/47031270/142679474-116915f0-83ac-4b22-8df5-201fc387e11c.png)

When I do rostopic list I see this: 
![image](https://user-images.githubusercontent.com/47031270/142679727-8dbe730d-fc30-40a8-81c3-a4b544b62318.png)

When I do echo /velodyne_packets I see the packets however I cannot see them on rviz. 

I tried running the velodyne_pointcloud package I see this:
![image](https://user-images.githubusercontent.com/47031270/142680047-ec0ee6c9-fe2f-4a22-99a2-ea09f1db7873.png)

When I do rostopic list I see /velodyne_points and I do echo but I do not see anything:
![image](https://user-images.githubusercontent.com/47031270/142680250-93cecdc0-6c1e-4ab4-bb08-df6af5eeb102.png)

I tried running the velodyne_laserscan I see this:
![image](https://user-images.githubusercontent.com/47031270/142680748-5a8e70b3-cad3-4e68-9e0d-9cdb605b5049.png)

When I do rostopic list I see /velodyne_points and /scan and I try to echo both the topic but I cannot see any data. 
![image](https://user-images.githubusercontent.com/47031270/142680960-6ffd2914-655d-4e54-ae73-61bfb98672ee.png)

I am not sure how to proceed. I tried the same with with the ros2 branch and I see the same things. Can someone help with letting me know the packages I need to run to be able to see topics /velodyne_points and /scan on Rviz

Thank you for the help 
Haritha

**Comment by bclaw524** [comment]
I am also having a similar issue. 

I can get the topic data using ros1, but not really sure how to proceed with ros2.

**Comment by bclaw524** [comment]
and in regular fashion, the moment I ask, I find the solution.

For any other newbies stuck, you'll want to use:

`ros2 launch velodyne velodyne-all-nodes-VLP16-launch.py`

**Comment by NadimDeeb** [comment]
> > I am also having a similar issue.
> > I can get the topic data using ros1, but not really sure how to proceed with ros2.
> > Any follow up on how to solve this?
> 
> and in regular fashion, the moment I ask, I find the solution.
> 
> For any other newbies stuck, you'll want to use:
> 
> `ros2 launch velodyne velodyne-all-nodes-VLP16-launch.py`

This really helped me thank you!

**Comment by JWhitleyWork** [comment]
Closing as resolved (should still be search-able so no information will be lost).
