### ISSUE TITLE
Octomapping using Velodyne PointCloud2 data maps rings

### ISSUE THREAD

**Issue by adityakolluru95** [ros-drivers/velodyne#444]
I tried to octomap a cube placed infront of a robot, with Velodyne HDL32 on top of the robot. The resultant map also includes the rings that are a part of the Velodyne output. Is there a way to exclude this **ring** parameter from the output? I even tried converting PointCloud2 to Point Cloud using pcl_ros conversions, but the results are same.
![Capture](https://user-images.githubusercontent.com/95696221/149341627-9613f37a-fd7d-4843-9e3b-e38a4c6fffbd.PNG)
![InkedCapture1_LI](https://user-images.githubusercontent.com/95696221/149341917-3560598f-b52e-419a-bb77-d38f7475f893.jpg)
The red marking encloses the robot, the yellow marking encloses the face of block, detected by the sensor.

**Comment by JWhitleyWork** [comment]
The rings you are seeing are returns from the lidar spread across the ground. This is not something that can be turned on or off but must be filtered by a ground filtering algorithm.
