### ISSUE TITLE
Installation on Foxy with sudo apt

### ISSUE THREAD

**Issue by floriankittelmann** [ros-drivers/velodyne#455]
**Please complete the following information:**
 - OS and Version: Ubuntu 20.04
 - ROS Version: Foxy
 - Built from Source or Downloaded from Official Repository: `sudo apt install ros-foxy-velodyne*`

**Describe the bug**
The packages are not available to run. `ros2 pkg list | grep velodyne` doesnt return anything. Do I need to build from source to run the velodyne node for ROS2 Foxy?

**To Reproduce**
1. `sudo apt install ros-foxy-velodyne*`
2. `ros2 pkg list | grep velodyne`
3. `ros2 launch velodyne_pointcloud 32e_points.launch`

**Expected behavior**
`ros2 launch velodyne_pointcloud 32e_points.launch` should be possible but returns that package not found

```
florian@ubuntu~$ ros2 launch velodyne_pointcloud 32e_points.launch
Package 'velodyne_pointcloud' not found: "package 'velodyne_pointcloud' not found, searching: ['/home/florian/ros2_foxy/ros2-linux']"
```

**Comment by JWhitleyWork** [comment]
@floriankittelmann It looks like you might not be sourcing your Foxy install folder first. You need to make sure that you run `source /opt/ros/foxy/setup.bash` before attempting to use a `ros2` command. If this is the only version of ROS that you use, I recommend just adding `source /opt/ros/foxy/setup.bash` to the end of your `~/.bashrc` file. Please let me know if this resolves your issue.

**Comment by floriankittelmann** [comment]
@JWhitleyWork Thank you for the hint! I was assuming that `. ~/ros2_foxy/ros2-linux/setup.bash` is enough to source the Foxy installation. But it seems `source /opt/ros/foxy/setup.bash` is also necessary. Unfortunately it was not described in the installation guide of Foxy https://docs.ros.org/en/foxy/Installation/Ubuntu-Install-Binary.html

**Comment by songanz** [comment]
Hi, I cannot find the `32e_points.launch` for ros foxy. Could you please share the file? Thank you so much!
