### ISSUE TITLE
Release for Humble

### ISSUE THREAD

**Issue by cocharland** [ros-drivers/velodyne#465]
**Please complete the following information:**
 - OS and Version: Ubuntu 22.04
 - ROS Version: Humble
 - Built from Source or Downloaded from Official Repository:
 - Version:  Built from Source: fdb9b47d46ad1660d6cf8383dcca1e869f06cdae

**Describe the bug**
The velodyne drivers are not released to humble yet

**To Reproduce**
1. attempt to install the velodyne package from the debians e.g.  `sudo apt install ros-humble-velodyne`
2. see that is fails due to the packages not being released
**Expected behavior**

Expect that the velodyne drivers are released for humble through apt

**Additional context**
The drivers build from the current head of the ros2 branch, and work with a VLP-16 that I have around to test with. If there is anything that needs doing to help get this released I have time open to help.

**Comment by JWhitleyWork** [comment]
https://github.com/ros/rosdistro/pull/33802

Just waiting for [package sync](https://discourse.ros.org/t/humble-sync/26441).
