### ISSUE TITLE
How to lower the min_range further

### ISSUE THREAD

**Issue by Jae-Seung-Jeon** [ros-drivers/velodyne#467]
Hi, I want to get points **within 0.5m** around Velodyne Puck.

So I changed all the values of **min_range** 
in [velodyne/velodyne_pointcloud/cfg/**TransformNode.cfg**] - gen.add(... **0.9**, 0.1, 10.0) **->** gen.add(... **0.0**, 0.1, 10.0),
and [velodyne/velodyne_pointcloud/launch/**VLP16_points.launch**] - **min_range** - **default="0.4" -> default="0.0"**
[velodyne/velodyne_pointcloud/launch/**transform_nodelet.launc**h] - **min_range** - **default="0.9" -> default="0.0"**

However, there are still no points less than 0.5m in Rviz.
Where should I modify?
Thank you.

**Comment by JWhitleyWork** [comment]
This is a hardware limitation, not a software one. No spinning Velodyne lidar will return points less than 0.5m away from the sensor.
