### ISSUE TITLE
sending the output via UDP

### ISSUE THREAD

**Issue by urbansound8K** [ros-drivers/velodyne#472]
Hi there!
a new user of ROS and having Velodyne 32

I am wondering if is there any tutorial explaining how to send the output of the Velodyne node via UDP

what I am doing is that I have been able to build autoware with jetson Xavier and using lidar only to detect and track objects
the only thing I need to figure out is how to send the XYZ via UDP, please?

**Comment by JWhitleyWork** [comment]
This is beyond the scope of this driver. You would need to convert the contents of the PointCloud2 message into UDP packets. I recommend creating your own ROS node to do this.
