### ISSUE TITLE
lidar data dosen't contain fields: name: "time" , how to get name: "time"?

### ISSUE THREAD

**Issue by JACKLiuDay** [ros-drivers/velodyne#477]
Hi, thank you for your great. I have two velodyne16. When I run them. I found some problem. 
![微信图片_20220915113214](https://user-images.githubusercontent.com/30967867/190307668-0959699d-b88d-43ae-a13f-4152278dd2ff.jpg)
![微信图片_20220915113218](https://user-images.githubusercontent.com/30967867/190307683-56063e81-957b-4ff3-ae5a-3cc22dc46ef8.jpg)
One has fields: name: "time" . While the other lidar does not have fields: name : "time". I want to use the lidar with fields:name: "time". Can you give me some help.

**Comment by wwdlh** [comment]
你好，我遇到了和你相同的问题，请问你是怎么解决的啊

**Comment by JACKLiuDay** [comment]
> 你好，我遇到了和你相同的问题，请问你是怎么解决的啊

时间有点久，我记不太清了，换下驱动试试

**Comment by Hliu0313** [comment]
已解决，最新驱动包含了 time 信息。
