### ISSUE TITLE
How to convert velodyne_points to velodyne_packets?

### ISSUE THREAD

**Issue by gara-9527** [ros-drivers/velodyne#478]
Hi！
I recorded a rosbag，and what I want is velodyne_packets but I record velodyne_points. Is there any way to convert velodyne_points to  velodyne_packets?
Your prump reply will be much appreciate! : )

**Comment by JWhitleyWork** [comment]
Unfortunately, the driver is not capable of going the other direction. In fact, it is not possible to completely recreate the packets from the points as the conversion from packets to points loses information.
