### ISSUE TITLE
can i  know the exact coordinate when  vlp16 is on?  through ros

### ISSUE THREAD

**Issue by himhan34** [ros-drivers/velodyne#488]
**Please complete the following information:**
 - OS and Version: ubuntu  18.04
 - ROS Version: melodic
 
can i  know the exact coordinate of  vlp16  lidar when  i  use  ros  driver  in the ros?   

and can i  know the  orientation  of vlp 16??

**Comment by JWhitleyWork** [comment]
I'm sorry, but there is no way to do this. The sensor itself does not have a way to determine it's orientation relative to any outside object or surface. You must measure this and publish a TF to use the transform.
