### ISSUE TITLE
ARM Binaries

### ISSUE THREAD

**Issue by Udit8348** [ros-drivers/velodyne#503]
**Is your feature request related to a problem? Please describe.**
When installing `ros-humble-velodyne-simulator` on Ubuntu 22.04 ARM64 the package is unavailable. It is likely that there are no ARM / AARCH compatible binaries so `ros dep` fails when trying to resolve this dependency.

**Describe the solution you'd like**
A solution to this problem would be to determine how to build this package for ARM.

**Describe alternatives you've considered**
Tried to place this repo in the project that I am working on, and `colcon build` but it does not recognize this package, nor does it try to compiler.

**Additional context**
Running Ubuntu ARM via Parallels Desktop on M1 Macbook Pro

**Comment by JWhitleyWork** [comment]
@Udit8348 I'm sorry but `velodyne_simulator` is not part of the `velodyne` repository. It appears to be hosted here: https://github.com/lmark1/velodyne_simulator. However, this repository appears to have been last updated in May of 2021 so I doubt there has been a Humble release for the package. Please post an issue in that repository.
