### ISSUE TITLE
std::bad_array_new_length error while mapping 

### ISSUE THREAD

**Issue by Arunkumar-ARi** [ros-drivers/velodyne#507]
**Please complete the following information:**
 - OS and Version: 18.04
 - ROS Version: Melodic
 - Built from Source or Downloaded from Official Repository: Downloaded
 - Version: #

**Describe the bug**
I am running velodyne_pointcloud package and using VLP16_points.launch file , and using that package I am trying to generate a map using gmapping package but I am ending up with the below error ,

```
terminate called after throwing an instance of  'std::bad_array_new_length' 
what(): std::bad_array_new_length
[slam_gmapping-1] process has died [ exit code -6].
```

**To Reproduce**
1. run roslaunch velodyne_pointcloud VLP16_points.launch 
2. run roslaunch gmapping gmap.launch

You can see the error in the terminal itself.

**Expected behavior**
I need to build a map using gmapping package.

**Comment by JWhitleyWork** [comment]
@Arunkumar-ARi I'm sorry but this looks to be an error with the `slam_gmapping` package rather than this driver. Additionally, Melodic is no longer a supported environment. If you will continue to use ROS1, please upgrade to Noetic.
