### ISSUE TITLE
[ WARN] [1685093610.943024678]: Velodyne poll() timeout

### ISSUE THREAD

**Issue by NadimDeeb** [ros-drivers/velodyne#511]
**Please complete the following information:**
 - OS and Version: Ubuntu 20
 - ROS Version: Noetic
 - Built from Source or Downloaded from Official Repository: Downloaded from Official Repo
 - Version: from master branch

**Describe the bug**
I keep getting the [ WARN] [1685093610.943024678]: Velodyne poll() timeout message and /velodyne_points is not showing any data

**To Reproduce**
1. Run roslaunch velodyne_pointcloud VLP16_points.launch
2.  The [ WARN] [1685093610.943024678]: Velodyne poll() timeout messages keeps popping up
3. then run rostopic echo /velodyne_points
4. No data echoed
5. Nothing shows up in Rviz

**Expected behavior**
I expected it to map the environment

**Additional context**

**Comment by JWhitleyWork** [comment]
@NadimDeeb This is not a bug. This can happen for many reasons including incorrect IP address configuration, incorrect port configuration, a bad cable, etc. Please check your physical configuration and validate data flow with a network analysis tool like Wireshark.
