### ISSUE TITLE
Velodyne VLS128 LiDAR data at 1200RPM is not coming at 360 degree field of view. 

### ISSUE THREAD

**Issue by abhishekt711** [ros-drivers/velodyne#515]
When I set RPM at 1200 in the launch file then data is recording at 20Hz, but when I visualize each pcd file it gives only 180 degree field of view. How to get complete 360 degree field of view data at 20Hz ?

**Comment by JWhitleyWork** [comment]
Did you actually modify the setting on the Velodyne? The RPM value in the driver does not change the hardware configuration, it is only to *match* the hardware configuration.

**Comment by abhishekt711** [comment]
here the Max RPM it is showing is 600RPM
![Screenshot from 2023-05-29 16-28-32](https://github.com/ros-drivers/velodyne/assets/36338604/08a24685-5a8d-40f3-964e-16da9e79947b)

**Comment by abhishekt711** [comment]
> Did you actually modify the setting on the Velodyne? The RPM value in the driver does not change the hardware configuration, it is only to _match_ the hardware configuration.

as you can see in the above pic that the max RPM is 600. unable to set the value of RPM more than 600

**Comment by JWhitleyWork** [comment]
Then setting the driver to 1200 RPM will not work. Sorry.

**Comment by abhishekt711** [comment]
> Then setting the driver to 1200 RPM will not work. Sorry.

Can I change the max RPM value to 1200 on web interface by contacting velodyne? Is there any way to do it ? Or this sensor supports upto 600RPM only.
