### ISSUE TITLE
Possible wrong type

### ISSUE THREAD

**Issue by stagecity** [ros-drivers/velodyne#52]
Hello,

there is a possible wrong type in velodyne_pointcloud rawdata.h for VLP16.
Original code is : 
  static const int VLP16_BLOCK_TDURATION = 110.592;
  static const int VLP16_DSR_TOFFSET = 2.304;
  static const int VLP16_FIRING_TOFFSET = 55.296;

Corrected code would be :   
  static const float VLP16_BLOCK_TDURATION = 110.592f;
  static const float VLP16_DSR_TOFFSET = 2.304f;
  static const float VLP16_FIRING_TOFFSET = 55.296f;

Sincerely

**Comment by jack-oquin** [comment]
Your comment looks right to me. Assuming the fractional values are correct, typing them as ``int`` causes undesired truncation.

**Comment by jack-oquin** [comment]
This is fixed now in ``master``. Please test to confirm, and re-open if there is still a problem
