### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by droter** [ros-drivers/velodyne#54]
Hi,

I cloned the source and tried to compile but I am getting this error:

catkin_ws/src/velodyne/velodyne_driver/include/velodyne_driver/input.h:36:18: fatal error: pcap.h: No such file or directory
 #include <pcap.h>

I am running Indigo on Ubuntu 14.04.

Thanks,

Matt

**Comment by jack-oquin** [comment]
You are missing one of the dependencies, libpcap-dev.

**Comment by jack-oquin** [comment]
A generally useful way to install all the dependencies of everything in your catkin workspace that's not already resolved within that workspace:

```
cd ~/catkin_ws
rosdep install --from-paths src --ignore-src --rosdistro indigo -y
```

Please close this issue if that fixes your problem.

**Comment by droter** [comment]
Thanks for your help.

Yes, after installing the dependencies I was able to build.

Matt

**Comment by firesnow1234** [comment]
How about Ubuntu16.04 in this issues？

**Comment by JWhitleyAStuff** [comment]
The instructions provided above resolve this issue on Ubuntu 14.04, 16.04, and 18.04.
