### ISSUE TITLE
Velodyne pointcloud node for HDL 32  doesn't seem to run?

### ISSUE THREAD

**Issue by srirambadri** [ros-drivers/velodyne#83]
I have a HDL 32 and a VLP 16. So when I try to run the roslaunch or the pointcloud node I get the following error?

 

$ rosrun velodyne_pointcloud cloud_node _calibration:=32db.yaml
[ INFO] [1458049427.031892132]: correction angles: 32db.yaml
YAML Exception: yaml-cpp: error at line 0, column 0: bad conversion
[ERROR] [1458049427.036928149]: Unable to open calibration file: 32db.yaml
[ INFO] [1458049427.043593822]: Reconfigure Request

YAML Exception: yaml-cpp: error at line 0, column 0: bad conversion

Can anyone pls suggest what I should be doing to solve this?

**Comment by jack-oquin** [comment]
Where is your calibration file? Is there a ``32db.yaml`` in the directory from which you are running the cloud node?

**Comment by jack-oquin** [comment]
This looks similar to another recent bug, see #84.

Please report whether the latest master fixes your problem.

**Comment by srirambadri** [comment]
Hi Jack,

Thanks a lot. Ya the error is fixed now.

**Comment by jack-oquin** [comment]
Good. Thanks for verifying it.
