### ISSUE TITLE
Unable to open calibration file  VLP16db.yaml

### ISSUE THREAD

**Issue by onlytailei** [ros-drivers/velodyne#84]
Unable to open calibration file: /home/tyler/catkin_ws/src/velodyne/velodyne_pointcloud/params/VLP16db.yaml

That's why?

**Comment by srirambadri** [comment]
I had the same problem with the HDL32db.yaml file

**Comment by onlytailei** [comment]
By the way, I use ubuntu 14.04 and ros indigo

**Comment by onlytailei** [comment]
@srirambadri 
Hi, I tried to install this pkg in Ubuntu 12.04 with Ros Hydro. Fortunately, it worked. So I guess it should be the problem of yaml-cpp version.

**Comment by srirambadri** [comment]
@onlytailei 
hi, 
thanks.

**Comment by jack-oquin** [comment]
What is the question? Is this a bug report?

If so, what did you do, and what went wrong?

**Comment by jack-oquin** [comment]
OK, this is a bug, and I can reproduce it. It was apparently caused by some recent updates to the YAML file reader.

As a workaround, try checking out commit 79c8d82, which precedes those changes.

**Comment by jack-oquin** [comment]
Let me know if that version works for you.

**Comment by jack-oquin** [comment]
xref: #82, #80

**Comment by jack-oquin** [comment]
@onlytailei and @srirambadri: Please check out the latest master containing fbe603a. I think it should fix your problem.

@wjwwood: Please code review this change. It seems to work again for the 32E, VLP-16 and the older 64E (with integer intensities), but fails to read the 64E_s2.1 calibration (containing float intensities).

**Comment by andrepfr** [comment]
@jack-oquin: Thanks for the fix. Worked for me with the VLP-16.

**Comment by onlytailei** [comment]
Thanks! I will check it soon.

**Comment by jack-oquin** [comment]
@wjwwood: The gtest added by c3e5178 demonstrates the failure of my latest attempt to handle your test case and also the example HDL-64 S2.1 YAML configuration. Both contain float intensities, so my latest fix does not solve your original problem.

I am still looking for a solution that works for both. That would be simpler if we only had to support one yaml-cpp API.

**Comment by wjwwood** [comment]
Hmm, sorry this change has caused so many issues. @jack-oquin are there unit tests that fail in each configuration? I can pretty easily switch between yaml-cpp 0.3 and yaml-cpp 0.5.

I could also try to change the yaml-cpp rosdep rule for OS X, now that indigo is the oldest supported platform. But the question is which is more work, fixing this problem or changing the rule.

**Comment by jack-oquin** [comment]
@wjwwood: No worries. Besides, I think I have fixed it now. 

YAML has a scalar type, but does not directly distinguish ``float`` from ``int``. So, my solution (9a5d583) is to always read intensities into a ``float``, then convert to the desired ``int``. 

That works for me with the 0.5 API. I think it should work with 0.3 as well. Please try it on OSX to verify.

My unit test coverage is adequate for this now, it includes both ``float`` and ``int`` intensity values. Just run: 
```
make run_tests_velodyne_pointcloud_gtest
```

**Comment by wjwwood** [comment]
Works for me on master. Thanks @jack-oquin.

**Comment by jack-oquin** [comment]
@wjwwood: Your change led to several significant improvements for both continuous integration and unit test coverage. And, you fixed a long-standing bug that I had not looked at at all.

I appreciate your contribution.
