### ISSUE TITLE
Connect two HDL 32e together

### ISSUE THREAD

**Issue by srirambadri** [ros-drivers/velodyne#85]
Hey,

I have two HDL 32e velodyne laser scanners and I connected them using a switch to my computer.

I ran the velodyne package and I'm getting the pointcloud.

The problem is both the pointclouds of the different HDL's are getting combined.

Is there a possibility to seperate the pointclouds?

**Comment by jack-oquin** [comment]
As already answered on answers.ros.org, you can use the ``device_ip`` parameter.

Did that solve your problem?

**Comment by srirambadri** [comment]
thanks, I use this to separate the pointclouds

**Comment by jack-oquin** [comment]
Can you suggest where the documentation could be improved to describe that parameter better?

For example, it seems to be missing from the [velodyne_driver wiki page](http://wiki.ros.org/velodyne_driver?distro=indigo#Parameters) parameter list.

**Comment by srirambadri** [comment]
As suggested in answers.ros.org, I added two parameters to the nodules_manager.launch file namely , device_ip and port.

I then set the parameters in the main launch file i.e., 32 e_points.launch.

**Comment by jack-oquin** [comment]
I updated the [parameter documentation](http://wiki.ros.org/velodyne_driver#Parameters). Please review, and let me know whether it seems clear.

**Comment by srirambadri** [comment]
Perfect. thanks
