### ISSUE TITLE
need ROS Jade release

### ISSUE THREAD

**Issue by jack-oquin** [ros-drivers/velodyne#86]
This will follow the Indigo release mentioned in #59. 

After that, we can make some changes that do not seem necessary or desirable for Indigo, which has already been in widespread use for almost two years.

**Comment by jack-oquin** [comment]
Since this is not a long-term distribution and no one has requested it (yet), this is lower-priority than #93.

**Comment by kmhallen** [comment]
It looks like we missed Jade. This issue can probably be closed.  
https://discourse.ros.org/t/final-jade-sync-2017-09-03/2559

**Comment by JWhitleyAStuff** [comment]
A new release is here! v1.3.0 was pushed to public last week.
