### ISSUE TITLE
velodyne_points messages only 3Hz for 600rpm

### ISSUE THREAD

**Issue by chiyuan-goh** [ros-drivers/velodyne#87]
Following the Ros tutorial for velodyne 32E, I can only see 3+Hz of messages from roslaunch velodyne_pointcloud 32e_points.launch, but it is set to 600 RPM and I verified it on the firmware builtin diagnostics page. 

Any idea?

**Comment by jack-oquin** [comment]
What is the rate of the packets topic?
```
rostopic hz /velodyne_packets

**Comment by chiyuan-goh** [comment]
Terribly sorry. There's a problem with switch. Once I swapped it out, worked just fine.

**Comment by jack-oquin** [comment]
No problem. Glad you got it working.
